In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
# # Install dependencies and ensure the latest version is used
# !pip install --upgrade kagglehub

# import kagglehub
# import os
# import importlib

# # Force reload the module to apply the upgrade without a manual restart
# importlib.reload(kagglehub)

# # Define the dataset identifier
# dataset_id = "nhanayai/shrimpdiseaseimagebd"
# # Define the destination folder in Google Drive
# download_path = "/content/drive/MyDrive/shrimp_disease_images"

# # Create the directory if it doesn't exist
# os.makedirs(download_path, exist_ok=True)

# # Download the latest version to the specified path
# # In the latest kagglehub, dataset_download is the standard method
# path = kagglehub.dataset_download(dataset_id)

# # Move or copy files to the desired Drive location if they aren't already there
# print(f"Dataset downloaded to temporary location: {path}")

# # To specifically ensure it is in your Drive folder:
# import shutil
# if os.path.exists(path):
#     for item in os.listdir(path):
#         s = os.path.join(path, item)
#         d = os.path.join(download_path, item)
#         if os.path.isdir(s):
#             shutil.copytree(s, d, dirs_exist_ok=True)
#         else:
#             shutil.copy2(s, d)

# print(f"Successfully synced dataset to Drive: {download_path}")

In [4]:
cd /content/drive/MyDrive/shrimp_disease_images/ShrimpDiseaseImageBD An Image Dataset for Computer Vision-Based Detection of Shrimp Diseases in Bangladesh/Root/Raw Images/Raw Images

/content/drive/MyDrive/shrimp_disease_images/ShrimpDiseaseImageBD An Image Dataset for Computer Vision-Based Detection of Shrimp Diseases in Bangladesh/Root/Raw Images/Raw Images

In [5]:
ls

'1. Healthy'/  '2. BG'/  '3. WSSV'/  '4. WSSV_BG'/

In [6]:
# !pip install rembg[gpu]

In [7]:
# import os
# import cv2
# import numpy as np
# from rembg import remove
# from PIL import Image
# from tqdm import tqdm

# # Original dataset path
# SOURCE_DIR = r'/content/drive/MyDrive/shrimp_disease_images/ShrimpDiseaseImageBD An Image Dataset for Computer Vision-Based Detection of Shrimp Diseases in Bangladesh/Root/Raw Images/Raw Images'

# # New directory to save the cleaned images
# DEST_DIR = r'/content/drive/MyDrive/shrimp_disease_images/Processed_Rembg_Images'

# def preprocess_dataset():
#     if not os.path.exists(DEST_DIR):
#         os.makedirs(DEST_DIR)

#     classes = ['1. Healthy', '2. BG', '3. WSSV', '4. WSSV_BG']

#     for cls in classes:
#         src_cls_dir = os.path.join(SOURCE_DIR, cls)
#         dest_cls_dir = os.path.join(DEST_DIR, cls)

#         if not os.path.exists(dest_cls_dir):
#             os.makedirs(dest_cls_dir)

#         if not os.path.isdir(src_cls_dir):
#             continue

#         images = [f for f in os.listdir(src_cls_dir) if f.lower().endswith(('.png', '.jpg', '.jpeg'))]
#         print(f"Processing {len(images)} images for class: {cls}")

#         for img_name in tqdm(images):
#             src_path = os.path.join(src_cls_dir, img_name)
#             dest_path = os.path.join(dest_cls_dir, img_name)

#             # Skip if already processed
#             if os.path.exists(dest_path):
#                 continue

#             try:
#                 # Read, remove background, and save
#                 image = cv2.imread(src_path)
#                 image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
#                 pil_img = Image.fromarray(image)
#                 clean_img = remove(pil_img).convert('RGB')

#                 # Save back as BGR for CV2 consistency if needed, or save directly via PIL
#                 clean_img.save(dest_path)
#             except Exception as e:
#                 print(f"Error processing {img_name}: {e}")

# # Execute the preprocessing
# preprocess_dataset()
# print(f"Preprocessing complete. Clean images saved to {DEST_DIR}")

## Baseline model comparison with LiteRT export

This section replaces the previous single-model training run with a controlled baseline comparison. The earlier cells still handle Drive mounting, dataset download, and the notebook's existing `rembg` preprocessing into `Processed_Rembg_Images`.

Models are trained one at a time:

- `mobilenet_v3_large`
- `efficientnet_b0`
- `yolo11n-cls`
- `yolo11m-cls`
- `yolo26n-cls`
- `yolo26m-cls`

The comparison follows the benchmark notebook's core training parameters (`224x224`, batch size `32`, AdamW/learning-rate `1e-4` where using PyTorch, `15` epochs, patience `3`) while using this notebook's processed-image input. Validation and test F1 are reported as **macro F1** so each shrimp disease class contributes equally.

A fixed stratified image-level `70/15/15` split is used for every model. This prevents class-ratio drift between models, but it does not guarantee specimen-level leakage protection if several photos of the same shrimp exist under different filenames. Treat results as an image-level baseline unless a specimen/group split is added later.

After each model is trained, the notebook attempts LiteRT/TFLite export. If TFLite conversion fails, it falls back to ONNX and records the export status in the final table.

In [8]:
# Install comparison/export dependencies used by the baseline section.
# Ultralytics is used for YOLO classification training and YOLO TFLite export.
# litert-torch is used for best-effort PyTorch -> LiteRT/TFLite conversion; ONNX is the fallback.
import sys, subprocess, importlib.util

packages = [
    "torchmetrics",
    "ultralytics>=8.3.0",
    "onnx",
    "onnxscript",
    "litert-torch",
]

def import_name_for(package_spec: str) -> str:
    package = package_spec.split(">=")[0].split("==")[0]
    mapping = {
        "litert-torch": "litert_torch",
        "onnxscript": "onnxscript",
    }
    return mapping.get(package, package.replace("-", "_"))

missing = []
for pkg in packages:
    if importlib.util.find_spec(import_name_for(pkg)) is None:
        missing.append(pkg)

if missing:
    print("Installing missing comparison/export dependencies:", missing)
    subprocess.check_call([sys.executable, "-m", "pip", "install", "-q", "-U", *missing])
else:
    print("All comparison/export dependencies are already available.")

Installing missing comparison/export dependencies: ['torchmetrics', 'ultralytics>=8.3.0', 'onnx', 'onnxscript', 'litert-torch']

In [9]:
import os
import gc
import json
import random
import shutil
import time
from pathlib import Path

import numpy as np
import pandas as pd
import torch
import torch.nn as nn
import torch.optim as optim
import torchmetrics
import torchvision.models as tv_models
from PIL import Image
from sklearn.model_selection import train_test_split
from torch.utils.data import Dataset, DataLoader
from torchvision import transforms
from tqdm import tqdm
from ultralytics import YOLO

# ==============================================================================
# 1. Shared configuration
# ==============================================================================
SEED = 42
random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)
torch.cuda.manual_seed_all(SEED)
torch.backends.cudnn.deterministic = True

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")

IMG_SIZE = 224
BATCH_SIZE = 32
EPOCHS = 15
PATIENCE = 3
LR = 1e-4
NUM_WORKERS = 2

DATA_DIR = Path('/content/drive/MyDrive/shrimp_disease_images/Processed_Rembg_Images')
OUTPUT_DIR = Path('/content/drive/MyDrive/shrimp_disease_images/baseline_model_comparison')
CHECKPOINT_DIR = OUTPUT_DIR / 'checkpoints'
EXPORT_DIR = OUTPUT_DIR / 'exports'
YOLO_DATA_DIR = OUTPUT_DIR / 'yolo_dataset'
YOLO_RUNS_DIR = OUTPUT_DIR / 'yolo_runs'
REPORT_DIR = OUTPUT_DIR / 'reports'
for d in [CHECKPOINT_DIR, EXPORT_DIR, YOLO_DATA_DIR, YOLO_RUNS_DIR, REPORT_DIR]:
    d.mkdir(parents=True, exist_ok=True)

CLASS_DIRS = ['1. Healthy', '2. BG', '3. WSSV', '4. WSSV_BG']
CLASS_NAMES = ['Healthy', 'BG', 'WSSV', 'WSSV_BG']
CLASS_TO_IDX = {folder: idx for idx, folder in enumerate(CLASS_DIRS)}
NUM_CLASSES = len(CLASS_DIRS)

PYTORCH_MODELS = ['mobilenet_v3_large', 'efficientnet_b0']
YOLO_MODELS = ['yolo11n-cls', 'yolo11m-cls', 'yolo26n-cls', 'yolo26m-cls']
ALL_MODELS = PYTORCH_MODELS + YOLO_MODELS
EXPORT_SMOKE_TEST_ONLY = False  # Set True to test exports without training any baseline models.

# ==============================================================================
# 2. Dataset discovery and fixed stratified split
# ==============================================================================
def discover_processed_images(data_dir: Path) -> pd.DataFrame:
    rows = []
    for class_dir in CLASS_DIRS:
        folder = data_dir / class_dir
        if not folder.exists():
            print(f"Warning: missing class folder: {folder}")
            continue
        for p in sorted(folder.iterdir()):
            if p.suffix.lower() in {'.jpg', '.jpeg', '.png', '.bmp'}:
                rows.append({
                    'path': str(p),
                    'class_dir': class_dir,
                    'label': CLASS_TO_IDX[class_dir],
                })
    df = pd.DataFrame(rows)
    if df.empty:
        raise RuntimeError(f"No images found under {data_dir}. Run the preprocessing cell first.")
    return df

df = discover_processed_images(DATA_DIR)
print(f"Loaded {len(df)} processed images from {DATA_DIR}")
print(df['class_dir'].value_counts().reindex(CLASS_DIRS))

train_df, tmp_df = train_test_split(
    df,
    test_size=0.30,
    stratify=df['label'],
    random_state=SEED,
    shuffle=True,
)
val_df, test_df = train_test_split(
    tmp_df,
    test_size=0.50,
    stratify=tmp_df['label'],
    random_state=SEED,
    shuffle=True,
)

for name, split_df in [('train', train_df), ('val', val_df), ('test', test_df)]:
    print(f"{name}: {len(split_df)} images")
    print(split_df['class_dir'].value_counts().reindex(CLASS_DIRS).to_dict())

# Image-level leakage sanity check. This does not catch same-specimen near duplicates.
train_paths = set(train_df['path'])
val_paths = set(val_df['path'])
test_paths = set(test_df['path'])
assert train_paths.isdisjoint(val_paths)
assert train_paths.isdisjoint(test_paths)
assert val_paths.isdisjoint(test_paths)
print("Image-level split overlap check passed.")

transform = transforms.Compose([
    transforms.Resize((IMG_SIZE, IMG_SIZE)),
    transforms.ToTensor(),
    transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225]),
])

class ShrimpDataset(Dataset):
    def __init__(self, dataframe, transform=None):
        self.df = dataframe.reset_index(drop=True)
        self.transform = transform

    def __len__(self):
        return len(self.df)

    def __getitem__(self, idx):
        row = self.df.iloc[idx]
        image = Image.open(row['path']).convert('RGB')
        if self.transform is not None:
            image = self.transform(image)
        return image, int(row['label'])

def seed_worker(worker_id):
    worker_seed = SEED + worker_id
    np.random.seed(worker_seed)
    random.seed(worker_seed)

loader_generator = torch.Generator()
loader_generator.manual_seed(SEED)

train_loader = DataLoader(
    ShrimpDataset(train_df, transform),
    batch_size=BATCH_SIZE,
    shuffle=True,
    num_workers=NUM_WORKERS,
    pin_memory=True,
    worker_init_fn=seed_worker,
    generator=loader_generator,
)
val_loader = DataLoader(
    ShrimpDataset(val_df, transform),
    batch_size=BATCH_SIZE,
    shuffle=False,
    num_workers=NUM_WORKERS,
    pin_memory=True,
)
test_loader = DataLoader(
    ShrimpDataset(test_df, transform),
    batch_size=BATCH_SIZE,
    shuffle=False,
    num_workers=NUM_WORKERS,
    pin_memory=True,
)

# ==============================================================================
# 3. Shared metric, timing, and export helpers
# ==============================================================================
def macro_f1_metric():
    return torchmetrics.F1Score(task='multiclass', num_classes=NUM_CLASSES, average='macro').to(device)

def count_params(model) -> float:
    return sum(p.numel() for p in model.parameters()) / 1e6

def sanitize_name(name: str) -> str:
    return name.replace('/', '_').replace(' ', '_').replace('.', '_')

def build_torchvision_model(model_name: str):
    if model_name == 'mobilenet_v3_large':
        weights = tv_models.MobileNet_V3_Large_Weights.IMAGENET1K_V2
        model = tv_models.mobilenet_v3_large(weights=weights)
        model.classifier[3] = nn.Linear(model.classifier[3].in_features, NUM_CLASSES)
    elif model_name == 'efficientnet_b0':
        weights = tv_models.EfficientNet_B0_Weights.IMAGENET1K_V1
        model = tv_models.efficientnet_b0(weights=weights)
        model.classifier[1] = nn.Linear(model.classifier[1].in_features, NUM_CLASSES)
    else:
        raise ValueError(f"Unsupported PyTorch model: {model_name}")
    return model.to(device)

def evaluate_pytorch_model(model, loader, criterion=None, timed=False):
    model.eval()
    f1 = macro_f1_metric()
    correct = 0
    total = 0
    total_loss = 0.0

    if timed:
        dummy = torch.randn(1, 3, IMG_SIZE, IMG_SIZE, device=device)
        with torch.no_grad():
            for _ in range(3):
                model(dummy)
            if torch.cuda.is_available():
                torch.cuda.synchronize()
        start = time.time()
    else:
        start = None

    with torch.no_grad():
        for ims, gts in loader:
            ims = ims.to(device, non_blocking=True)
            gts = gts.to(device, non_blocking=True)
            logits = model(ims)
            if criterion is not None:
                total_loss += criterion(logits, gts).item() * ims.size(0)
            preds = torch.argmax(logits, dim=1)
            correct += (preds == gts).sum().item()
            total += gts.size(0)
            f1.update(logits, gts)

    if timed and torch.cuda.is_available():
        torch.cuda.synchronize()
    elapsed = time.time() - start if timed else None

    return {
        'loss': total_loss / max(1, total) if criterion is not None else None,
        'accuracy': correct / max(1, total),
        'macro_f1': f1.compute().item(),
        'elapsed': elapsed,
    }

def export_pytorch_model(model, model_name: str):
    model_cpu = model.to('cpu').eval()
    sample = torch.randn(1, 3, IMG_SIZE, IMG_SIZE)
    safe_name = sanitize_name(model_name)
    tflite_path = EXPORT_DIR / f'{safe_name}.tflite'
    onnx_path = EXPORT_DIR / f'{safe_name}.onnx'

    tflite_error_text = ''
    try:
        import litert_torch
        if hasattr(litert_torch, 'convert'):
            edge_model = litert_torch.convert(model_cpu, (sample,))
        elif hasattr(litert_torch, 'ai_edge_torch') and hasattr(litert_torch.ai_edge_torch, 'convert'):
            edge_model = litert_torch.ai_edge_torch.convert(model_cpu, (sample,))
        else:
            raise AttributeError('litert_torch does not expose a supported convert() API')

        if hasattr(edge_model, 'export'):
            edge_model.export(str(tflite_path))
        elif hasattr(edge_model, 'save'):
            edge_model.save(str(tflite_path))
        else:
            raise AttributeError('converted LiteRT model has neither export() nor save()')
        return 'tflite', str(tflite_path), ''
    except Exception as tflite_error:
        tflite_error_text = f'{type(tflite_error).__name__}: {tflite_error}'

    try:
        torch.onnx.export(
            model_cpu,
            sample,
            str(onnx_path),
            input_names=['input'],
            output_names=['logits'],
            dynamic_axes={'input': {0: 'batch'}, 'logits': {0: 'batch'}},
            opset_version=17,
            dynamo=False,
        )
        return 'onnx', str(onnx_path), f'TFLite failed: {tflite_error_text}'
    except TypeError:
        # Older PyTorch versions do not accept dynamo=False.
        try:
            torch.onnx.export(
                model_cpu,
                sample,
                str(onnx_path),
                input_names=['input'],
                output_names=['logits'],
                dynamic_axes={'input': {0: 'batch'}, 'logits': {0: 'batch'}},
                opset_version=17,
            )
            return 'onnx', str(onnx_path), f'TFLite failed: {tflite_error_text}'
        except Exception as onnx_error:
            return 'failed', '', f'TFLite failed: {tflite_error_text}; ONNX failed: {type(onnx_error).__name__}: {onnx_error}'
    except Exception as onnx_error:
        return 'failed', '', f'TFLite failed: {tflite_error_text}; ONNX failed: {type(onnx_error).__name__}: {onnx_error}'

def train_pytorch_baseline(model_name: str) -> dict:
    print('\n' + '=' * 80)
    print(f'Training PyTorch baseline: {model_name}')
    print('=' * 80)

    model = build_torchvision_model(model_name)
    optimizer = optim.AdamW(model.parameters(), lr=LR)
    criterion = nn.CrossEntropyLoss()
    best_f1 = -1.0
    epochs_no_improve = 0
    safe_name = sanitize_name(model_name)
    best_path = CHECKPOINT_DIR / f'best_{safe_name}.pth'
    train_start = time.time()

    for epoch in range(EPOCHS):
        model.train()
        train_loss = 0.0
        train_correct = 0
        train_total = 0
        for ims, gts in tqdm(train_loader, desc=f'{model_name} epoch {epoch + 1}/{EPOCHS}', leave=False):
            ims = ims.to(device, non_blocking=True)
            gts = gts.to(device, non_blocking=True)
            logits = model(ims)
            loss = criterion(logits, gts)

            optimizer.zero_grad(set_to_none=True)
            loss.backward()
            optimizer.step()

            train_loss += loss.item() * ims.size(0)
            train_correct += (torch.argmax(logits, dim=1) == gts).sum().item()
            train_total += gts.size(0)

        val_metrics = evaluate_pytorch_model(model, val_loader, criterion=criterion, timed=False)
        train_acc = train_correct / max(1, train_total)
        print(
            f"Epoch {epoch + 1:02d}/{EPOCHS} | "
            f"Train Loss: {train_loss / max(1, train_total):.4f} - Acc: {train_acc:.4f} | "
            f"Val Loss: {val_metrics['loss']:.4f} - Macro F1: {val_metrics['macro_f1']:.4f}"
        )

        if val_metrics['macro_f1'] > best_f1:
            best_f1 = val_metrics['macro_f1']
            epochs_no_improve = 0
            torch.save(model.state_dict(), best_path)
            print(f"  --> Saved best checkpoint: macro F1 {best_f1:.4f}")
        else:
            epochs_no_improve += 1
            print(f"  --> No improvement ({epochs_no_improve}/{PATIENCE})")

        if epochs_no_improve >= PATIENCE:
            print('  --> Early stopping triggered.')
            break

    train_time = time.time() - train_start
    model.load_state_dict(torch.load(best_path, map_location=device, weights_only=True))
    params_m = count_params(model)
    test_metrics = evaluate_pytorch_model(model, test_loader, criterion=None, timed=True)
    inf_time = test_metrics['elapsed']
    export_format, export_path, export_note = export_pytorch_model(model, model_name)
    model.to(device)

    result = {
        'Model': model_name,
        'Parameters (M)': round(params_m, 2),
        'Training Time (s)': round(train_time, 1),
        'Val F1-Score': round(best_f1, 4),
        'Test Accuracy': round(test_metrics['accuracy'], 4),
        'Test F1-Score': round(test_metrics['macro_f1'], 4),
        'Inference Time (s)': round(inf_time, 2),
        'FPS': round(len(test_df) / inf_time, 1),
        'Latency (ms)': round((inf_time / len(test_df)) * 1000, 2),
        'Export Format': export_format,
        'Export Path': export_path,
        'Export Note': export_note,
    }

    del model, optimizer
    if torch.cuda.is_available():
        torch.cuda.empty_cache()
    gc.collect()
    return result

# ==============================================================================
# 4. YOLO split preparation, training, evaluation, and export
# ==============================================================================
def prepare_yolo_dataset():
    if YOLO_DATA_DIR.exists():
        shutil.rmtree(YOLO_DATA_DIR)
    for split_name, split_df in [('train', train_df), ('val', val_df), ('test', test_df)]:
        for class_dir in CLASS_DIRS:
            (YOLO_DATA_DIR / split_name / class_dir).mkdir(parents=True, exist_ok=True)
        for _, row in split_df.iterrows():
            src = Path(row['path'])
            dst = YOLO_DATA_DIR / split_name / row['class_dir'] / src.name
            if dst.exists():
                stem = dst.stem
                suffix = dst.suffix
                dst = dst.with_name(f'{stem}_{abs(hash(str(src))) % 10_000_000}{suffix}')
            shutil.copy2(src, dst)
    print(f'Prepared YOLO classification dataset at {YOLO_DATA_DIR}')

prepare_yolo_dataset()

def yolo_device_arg():
    return 0 if torch.cuda.is_available() else 'cpu'

def evaluate_yolo_model(yolo_model, eval_df: pd.DataFrame, timed=False):
    names = yolo_model.names
    name_to_idx = {v: int(k) for k, v in names.items()}
    source_paths = eval_df['path'].tolist()

    if timed:
        # Warm up with one image. Keep this out of the measured interval.
        _ = yolo_model.predict(source=source_paths[:1], imgsz=IMG_SIZE, device=yolo_device_arg(), verbose=False)
        if torch.cuda.is_available():
            torch.cuda.synchronize()
        start = time.time()
    else:
        start = None

    preds = yolo_model.predict(
        source=source_paths,
        imgsz=IMG_SIZE,
        batch=BATCH_SIZE,
        device=yolo_device_arg(),
        verbose=False,
    )

    if timed and torch.cuda.is_available():
        torch.cuda.synchronize()
    elapsed = time.time() - start if timed else None

    y_true = torch.tensor([name_to_idx[c] for c in eval_df['class_dir'].tolist()], device=device)
    y_pred = torch.tensor([int(r.probs.top1) for r in preds], device=device)
    logits_for_metric = torch.nn.functional.one_hot(y_pred, num_classes=NUM_CLASSES).float()
    f1 = macro_f1_metric()
    f1.update(logits_for_metric, y_true)
    accuracy = (y_pred == y_true).float().mean().item()

    return {
        'accuracy': accuracy,
        'macro_f1': f1.compute().item(),
        'elapsed': elapsed,
    }

def export_yolo_model(yolo_model, model_name: str):
    try:
        exported = yolo_model.export(format='tflite', imgsz=IMG_SIZE)
        return 'tflite', str(exported), ''
    except Exception as tflite_error:
        try:
            exported = yolo_model.export(format='onnx', imgsz=IMG_SIZE)
            return 'onnx', str(exported), f'TFLite failed: {type(tflite_error).__name__}: {tflite_error}'
        except Exception as onnx_error:
            return 'failed', '', f'TFLite failed: {tflite_error}; ONNX failed: {onnx_error}'

def train_yolo_baseline(model_name: str) -> dict:
    print('\n' + '=' * 80)
    print(f'Training YOLO baseline: {model_name}')
    print('=' * 80)

    weights_name = f'{model_name}.pt'
    train_start = time.time()
    yolo = YOLO(weights_name)
    yolo.train(
        data=str(YOLO_DATA_DIR),
        task='classify',
        imgsz=IMG_SIZE,
        epochs=EPOCHS,
        batch=BATCH_SIZE,
        patience=PATIENCE,
        seed=SEED,
        project=str(YOLO_RUNS_DIR),
        name=sanitize_name(model_name),
        exist_ok=True,
        device=yolo_device_arg(),
        verbose=True,
    )
    train_time = time.time() - train_start

    best_path = YOLO_RUNS_DIR / sanitize_name(model_name) / 'weights' / 'best.pt'
    if not best_path.exists():
        # Fallback for Ultralytics version-specific save layouts.
        candidates = sorted((YOLO_RUNS_DIR / sanitize_name(model_name)).glob('**/best.pt'))
        if not candidates:
            raise FileNotFoundError(f'Could not locate YOLO best checkpoint for {model_name}')
        best_path = candidates[-1]

    best_yolo = YOLO(str(best_path))
    val_metrics = evaluate_yolo_model(best_yolo, val_df, timed=False)
    test_metrics = evaluate_yolo_model(best_yolo, test_df, timed=True)
    inf_time = test_metrics['elapsed']
    params_m = count_params(best_yolo.model)
    export_format, export_path, export_note = export_yolo_model(best_yolo, model_name)

    result = {
        'Model': model_name,
        'Parameters (M)': round(params_m, 2),
        'Training Time (s)': round(train_time, 1),
        'Val F1-Score': round(val_metrics['macro_f1'], 4),
        'Test Accuracy': round(test_metrics['accuracy'], 4),
        'Test F1-Score': round(test_metrics['macro_f1'], 4),
        'Inference Time (s)': round(inf_time, 2),
        'FPS': round(len(test_df) / inf_time, 1),
        'Latency (ms)': round((inf_time / len(test_df)) * 1000, 2),
        'Export Format': export_format,
        'Export Path': export_path,
        'Export Note': export_note,
    }

    del yolo, best_yolo
    if torch.cuda.is_available():
        torch.cuda.empty_cache()
    gc.collect()
    return result

# ==============================================================================
# 5. Export smoke tests before long training
# ==============================================================================
def run_export_smoke_tests():
    print('\n' + '=' * 80)
    print('EXPORT SMOKE TESTS')
    print('=' * 80)

    smoke_results = []

    # PyTorch smoke test: verifies LiteRT/TFLite attempt and ONNX fallback before training.
    try:
        smoke_model = build_torchvision_model('mobilenet_v3_large')
        with torch.no_grad():
            _ = smoke_model(torch.randn(1, 3, IMG_SIZE, IMG_SIZE, device=device))
        export_format, export_path, export_note = export_pytorch_model(smoke_model, 'smoke_mobilenet_v3_large')
        smoke_model.to(device)
        smoke_results.append({
            'Target': 'PyTorch mobilenet_v3_large',
            'Export Format': export_format,
            'Export Path': export_path,
            'Export Note': export_note,
        })
        del smoke_model
        if export_format == 'failed':
            raise RuntimeError(f'PyTorch export smoke test failed. {export_note}')
    except Exception as exc:
        smoke_results.append({
            'Target': 'PyTorch mobilenet_v3_large',
            'Export Format': 'failed',
            'Export Path': '',
            'Export Note': f'{type(exc).__name__}: {exc}',
        })

    # YOLO smoke test: pretrained tiny classifier export is the fastest way to catch exporter/package issues.
    try:
        smoke_yolo = YOLO('yolo11n-cls.pt')
        export_format, export_path, export_note = export_yolo_model(smoke_yolo, 'smoke_yolo11n-cls')
        smoke_results.append({
            'Target': 'YOLO yolo11n-cls',
            'Export Format': export_format,
            'Export Path': export_path,
            'Export Note': export_note,
        })
        del smoke_yolo
        if export_format == 'failed':
            raise RuntimeError(f'YOLO export smoke test failed. {export_note}')
    except Exception as exc:
        smoke_results.append({
            'Target': 'YOLO yolo11n-cls',
            'Export Format': 'failed',
            'Export Path': '',
            'Export Note': f'{type(exc).__name__}: {exc}',
        })

    smoke_df = pd.DataFrame(smoke_results)
    display(smoke_df)
    smoke_df.to_csv(REPORT_DIR / 'export_smoke_test_results.csv', index=False)

    hard_failures = smoke_df[smoke_df['Export Format'] == 'failed']
    if not hard_failures.empty:
        raise RuntimeError('Export smoke test failed. Fix exporter dependencies before training all models.')

    print('Export smoke tests passed. Continuing to baseline training.')

run_export_smoke_tests()

if EXPORT_SMOKE_TEST_ONLY:
    raise SystemExit('EXPORT_SMOKE_TEST_ONLY=True; stopping after export smoke tests by request.')

# ==============================================================================
# 5. Sequential comparison loop
# ==============================================================================
comparison_results = []
for model_name in ALL_MODELS:
    try:
        if model_name in PYTORCH_MODELS:
            result = train_pytorch_baseline(model_name)
        else:
            result = train_yolo_baseline(model_name)
        comparison_results.append(result)

        partial_df = pd.DataFrame(comparison_results)
        partial_df.to_csv(REPORT_DIR / 'baseline_model_comparison_partial.csv', index=False)
        print('Recorded result:')
        display(pd.DataFrame([result]))
    except Exception as exc:
        print(f'ERROR while running {model_name}: {type(exc).__name__}: {exc}')
        comparison_results.append({
            'Model': model_name,
            'Parameters (M)': np.nan,
            'Training Time (s)': np.nan,
            'Val F1-Score': np.nan,
            'Test Accuracy': np.nan,
            'Test F1-Score': np.nan,
            'Inference Time (s)': np.nan,
            'FPS': np.nan,
            'Latency (ms)': np.nan,
            'Export Format': 'failed',
            'Export Path': '',
            'Export Note': f'Run failed: {type(exc).__name__}: {exc}',
        })
        pd.DataFrame(comparison_results).to_csv(REPORT_DIR / 'baseline_model_comparison_partial.csv', index=False)

# ==============================================================================
# 6. Final table
# ==============================================================================
df_summary = pd.DataFrame(comparison_results)
if not df_summary.empty:
    df_summary = df_summary.sort_values(by='Test F1-Score', ascending=False, na_position='last').reset_index(drop=True)
    print('\n' + '=' * 80)
    print('BASELINE PERFORMANCE SUMMARY: SHRIMP DISEASE CLASSIFICATION')
    print('=' * 80)
    display(df_summary)
    csv_path = REPORT_DIR / 'baseline_model_comparison_summary.csv'
    json_path = REPORT_DIR / 'baseline_model_comparison_summary.json'
    df_summary.to_csv(csv_path, index=False)
    df_summary.to_json(json_path, orient='records', indent=2)
    print(f'Saved summary CSV: {csv_path}')
    print(f'Saved summary JSON: {json_path}')
else:
    print('No model results were produced.')

Creating new Ultralytics Settings v0.0.6 file ✅
View Ultralytics Settings with 'yolo settings' or at '/root/.config/Ultralytics/settings.json'
Update Settings with 'yolo settings key=value', i.e. 'yolo settings runs_dir=path/to/dir'. For help see https://docs.ultralytics.com/quickstart/#ultralytics-settings.
Using device: cuda
Loaded 1149 processed images from /content/drive/MyDrive/shrimp_disease_images/Processed_Rembg_Images
class_dir
1. Healthy    403
2. BG         198
3. WSSV       328
4. WSSV_BG    220
Name: count, dtype: int64
train: 804 images
{'1. Healthy': 282, '2. BG': 139, '3. WSSV': 229, '4. WSSV_BG': 154}
val: 172 images
{'1. Healthy': 60, '2. BG': 30, '3. WSSV': 49, '4. WSSV_BG': 33}
test: 173 images
{'1. Healthy': 61, '2. BG': 29, '3. WSSV': 50, '4. WSSV_BG': 33}
Image-level split overlap check passed.
Prepared YOLO classification dataset at /content/drive/MyDrive/shrimp_disease_images/baseline_model_comparison/yolo_dataset

================================================================================
EXPORT SMOKE TESTS
================================================================================
Downloading: "https://download.pytorch.org/models/mobilenet_v3_large-5c1a4163.pth" to /root/.cache/torch/hub/checkpoints/mobilenet_v3_large-5c1a4163.pth

100%|██████████| 21.1M/21.1M [00:00<00:00, 80.2MB/s]
/tmp/ipykernel_2328/1387526105.py:264: DeprecationWarning: You are using the legacy TorchScript-based ONNX export. Starting in PyTorch 2.9, the new torch.export-based ONNX exporter has become the default. Learn more about the new export logic: https://docs.pytorch.org/docs/stable/onnx_export.html. For exporting control flow: https://pytorch.org/tutorials/beginner/onnx/export_control_flow_model_to_onnx_tutorial.html
  torch.onnx.export(

Downloading https://github.com/ultralytics/assets/releases/download/v8.4.0/yolo11n-cls.pt to 'yolo11n-cls.pt': 100% ━━━━━━━━━━━━ 5.5MB 50.6MB/s 0.1s
Ultralytics 8.4.51 🚀 Python-3.12.13 torch-2.10.0+cu128 CPU (Intel Xeon CPU @ 2.00GHz)
💡 ProTip: Export to OpenVINO format for best performance on Intel hardware. Learn more at https://docs.ultralytics.com/integrations/openvino/
YOLO11n-cls summary (fused): 47 layers, 2,807,024 parameters, 0 gradients, 4.2 GFLOPs

PyTorch: starting from 'yolo11n-cls.pt' with input shape (1, 3, 224, 224) BCHW and output shape(s) (1, 1000) (5.5 MB)
requirements: Ultralytics requirements ['onnxslim>=0.1.71', 'onnxruntime-gpu'] not found, attempting AutoUpdate...
Using Python 3.12.13 environment at: /usr
Resolved 12 packages in 277ms
Prepared 3 packages in 2.77s
Installed 3 packages in 11ms
 + colorama==0.4.6
 + onnxruntime-gpu==1.26.0
 + onnxslim==0.1.93

requirements: AutoUpdate success ✅ 3.5s
WARNING ⚠️ requirements: Restart runtime or rerun command for updates to take effect


ONNX: starting export with onnx 1.21.0 opset 20...
ONNX: slimming with onnxslim 0.1.93...
ONNX: export success ✅ 5.5s, saved as 'yolo11n-cls.onnx' (10.8 MB)
requirements: Ultralytics requirements ['tf_keras<=2.19.0', 'sng4onnx>=1.0.1', 'onnx_graphsurgeon>=0.3.26', 'onnx2tf>=1.26.3,<1.29.0'] not found, attempting AutoUpdate...
Using Python 3.12.13 environment at: /usr
Resolved 42 packages in 4.39s
Prepared 6 packages in 15.07s
Uninstalled 3 packages in 971ms
Installed 6 packages in 383ms
 + onnx-graphsurgeon==0.6.1
 + onnx2tf==1.28.8
 + sng4onnx==2.0.1
 - tensorboard==2.20.0
 + tensorboard==2.19.0
 - tensorflow==2.20.0
 + tensorflow==2.19.1
 - tf-keras==2.20.0
 + tf-keras==2.19.0

requirements: AutoUpdate success ✅ 21.1s
WARNING ⚠️ requirements: Restart runtime or rerun command for updates to take effect


TensorFlow SavedModel: starting export with tensorflow 2.20.0...
Downloading https://github.com/ultralytics/assets/releases/download/v8.4.0/calibration_image_sample_data_20x128x128x3_float32.npy.zip to 'calibration_image_sample_data_20x128x128x3_float32.npy.zip': 100% ━━━━━━━━━━━━ 1.1MB 14.3MB/s 0.1s
Unzipping calibration_image_sample_data_20x128x128x3_float32.npy.zip to /content/drive/MyDrive/shrimp_disease_images/ShrimpDiseaseImageBD An Image Dataset for Computer Vision-Based Detection of Shrimp Diseases in Bangladesh/Root/Raw Images/Raw Images/calibration_image_sample_data_20x128x128x3_float32.npy...: 100% ━━━━━━━━━━━━ 1/1 24.5files/s 0.0s
TensorFlow SavedModel: starting TFLite export with onnx2tf 1.28.8...
Saved artifact at 'yolo11n-cls_saved_model'. The following endpoints are available:

* Endpoint 'serving_default'
  inputs_0 (POSITIONAL_ONLY): TensorSpec(shape=(1, 224, 224, 3), dtype=tf.float32, name='images')
Output Type:
  TensorSpec(shape=(1, 1000), dtype=tf.float32, name=None)
Captures:
  133868324035600: TensorSpec(shape=(4, 2), dtype=tf.int32, name=None)
  133868324030224: TensorSpec(shape=(3, 3, 3, 16), dtype=tf.float32, name=None)
  133868324034640: TensorSpec(shape=(16,), dtype=tf.float32, name=None)
  133868324039056: TensorSpec(shape=(4, 2), dtype=tf.int32, name=None)
  133868324040208: TensorSpec(shape=(3, 3, 16, 32), dtype=tf.float32, name=None)
  133868324039824: TensorSpec(shape=(32,), dtype=tf.float32, name=None)
  133868324040400: TensorSpec(shape=(1, 1, 32, 32), dtype=tf.float32, name=None)
  133868324040592: TensorSpec(shape=(32,), dtype=tf.float32, name=None)
  133868324029264: TensorSpec(shape=(4,), dtype=tf.int64, name=None)
  133868324035792: TensorSpec(shape=(4,), dtype=tf.int64, name=None)
  133868324042896: TensorSpec(shape=(3, 3, 16, 8), dtype=tf.float32, name=None)
  133868324043280: TensorSpec(shape=(8,), dtype=tf.float32, name=None)
  133868324041360: TensorSpec(shape=(3, 3, 8, 16), dtype=tf.float32, name=None)
  133868324042128: TensorSpec(shape=(16,), dtype=tf.float32, name=None)
  133868324034064: TensorSpec(shape=(4,), dtype=tf.int64, name=None)
  133868324041936: TensorSpec(shape=(4,), dtype=tf.int64, name=None)
  133868324044624: TensorSpec(shape=(1, 1, 48, 64), dtype=tf.float32, name=None)
  133868324043664: TensorSpec(shape=(64,), dtype=tf.float32, name=None)
  133868324041168: TensorSpec(shape=(4, 2), dtype=tf.int32, name=None)
  133868324044048: TensorSpec(shape=(3, 3, 64, 64), dtype=tf.float32, name=None)
  133868324042704: TensorSpec(shape=(64,), dtype=tf.float32, name=None)
  133868324044432: TensorSpec(shape=(1, 1, 64, 64), dtype=tf.float32, name=None)
  133868324043472: TensorSpec(shape=(64,), dtype=tf.float32, name=None)
  133868296880400: TensorSpec(shape=(4,), dtype=tf.int64, name=None)
  133868296880208: TensorSpec(shape=(4,), dtype=tf.int64, name=None)
  133868324044240: TensorSpec(shape=(3, 3, 32, 16), dtype=tf.float32, name=None)
  133868324043856: TensorSpec(shape=(16,), dtype=tf.float32, name=None)
  133868296882320: TensorSpec(shape=(3, 3, 16, 32), dtype=tf.float32, name=None)
  133868296881744: TensorSpec(shape=(32,), dtype=tf.float32, name=None)
  133868296880592: TensorSpec(shape=(4,), dtype=tf.int64, name=None)
  133868296880784: TensorSpec(shape=(4,), dtype=tf.int64, name=None)
  133868296882704: TensorSpec(shape=(1, 1, 96, 128), dtype=tf.float32, name=None)
  133868296882512: TensorSpec(shape=(128,), dtype=tf.float32, name=None)
  133868296883088: TensorSpec(shape=(4, 2), dtype=tf.int32, name=None)
  133868296881360: TensorSpec(shape=(3, 3, 128, 128), dtype=tf.float32, name=None)
  133868296882896: TensorSpec(shape=(128,), dtype=tf.float32, name=None)
  133868296883280: TensorSpec(shape=(1, 1, 128, 128), dtype=tf.float32, name=None)
  133868296883472: TensorSpec(shape=(128,), dtype=tf.float32, name=None)
  133868296884048: TensorSpec(shape=(4,), dtype=tf.int64, name=None)
  133868296883856: TensorSpec(shape=(4,), dtype=tf.int64, name=None)
  133868296885968: TensorSpec(shape=(1, 1, 64, 32), dtype=tf.float32, name=None)
  133868296886160: TensorSpec(shape=(32,), dtype=tf.float32, name=None)
  133868296885392: TensorSpec(shape=(3, 3, 32, 32), dtype=tf.float32, name=None)
  133868296886352: TensorSpec(shape=(32,), dtype=tf.float32, name=None)
  133868296886544: TensorSpec(shape=(3, 3, 32, 32), dtype=tf.float32, name=None)
  133868296886736: TensorSpec(shape=(32,), dtype=tf.float32, name=None)
  133868296885584: TensorSpec(shape=(3, 3, 32, 32), dtype=tf.float32, name=None)
  133868296887120: TensorSpec(shape=(32,), dtype=tf.float32, name=None)
  133868296885008: TensorSpec(shape=(3, 3, 32, 32), dtype=tf.float32, name=None)
  133868296881936: TensorSpec(shape=(1, 1, 64, 32), dtype=tf.float32, name=None)
  133868296887312: TensorSpec(shape=(32,), dtype=tf.float32, name=None)
  133868296883664: TensorSpec(shape=(32,), dtype=tf.float32, name=None)
  133868296887888: TensorSpec(shape=(1, 1, 64, 64), dtype=tf.float32, name=None)
  133868296886928: TensorSpec(shape=(64,), dtype=tf.float32, name=None)
  133868296884240: TensorSpec(shape=(4,), dtype=tf.int64, name=None)
  133868296884432: TensorSpec(shape=(4,), dtype=tf.int64, name=None)
  133868296888080: TensorSpec(shape=(1, 1, 192, 128), dtype=tf.float32, name=None)
  133868296888272: TensorSpec(shape=(128,), dtype=tf.float32, name=None)
  133868296888464: TensorSpec(shape=(4, 2), dtype=tf.int32, name=None)
  133868296887504: TensorSpec(shape=(3, 3, 128, 256), dtype=tf.float32, name=None)
  133868296887696: TensorSpec(shape=(256,), dtype=tf.float32, name=None)
  133868296888848: TensorSpec(shape=(1, 1, 256, 256), dtype=tf.float32, name=None)
  133868296889040: TensorSpec(shape=(256,), dtype=tf.float32, name=None)
  133868296889616: TensorSpec(shape=(4,), dtype=tf.int64, name=None)
  133868296889424: TensorSpec(shape=(4,), dtype=tf.int64, name=None)
  133868296891536: TensorSpec(shape=(1, 1, 128, 64), dtype=tf.float32, name=None)
  133868296891728: TensorSpec(shape=(64,), dtype=tf.float32, name=None)
  133868296890960: TensorSpec(shape=(3, 3, 64, 64), dtype=tf.float32, name=None)
  133868296891920: TensorSpec(shape=(64,), dtype=tf.float32, name=None)
  133868296892112: TensorSpec(shape=(3, 3, 64, 64), dtype=tf.float32, name=None)
  133868296892304: TensorSpec(shape=(64,), dtype=tf.float32, name=None)
  133868296891152: TensorSpec(shape=(3, 3, 64, 64), dtype=tf.float32, name=None)
  133868296892688: TensorSpec(shape=(64,), dtype=tf.float32, name=None)
  133868296890576: TensorSpec(shape=(3, 3, 64, 64), dtype=tf.float32, name=None)
  133868296888656: TensorSpec(shape=(1, 1, 128, 64), dtype=tf.float32, name=None)
  133868296892880: TensorSpec(shape=(64,), dtype=tf.float32, name=None)
  133868296889232: TensorSpec(shape=(64,), dtype=tf.float32, name=None)
  133868296893456: TensorSpec(shape=(1, 1, 128, 128), dtype=tf.float32, name=None)
  133868296892496: TensorSpec(shape=(128,), dtype=tf.float32, name=None)
  133868296889808: TensorSpec(shape=(4,), dtype=tf.int64, name=None)
  133868296890000: TensorSpec(shape=(4,), dtype=tf.int64, name=None)
  133868296893648: TensorSpec(shape=(1, 1, 384, 256), dtype=tf.float32, name=None)
  133868296893840: TensorSpec(shape=(256,), dtype=tf.float32, name=None)
  133868296893072: TensorSpec(shape=(1, 1, 256, 256), dtype=tf.float32, name=None)
  133868296894032: TensorSpec(shape=(256,), dtype=tf.float32, name=None)
  133868296893264: TensorSpec(shape=(1, 1, 128, 256), dtype=tf.float32, name=None)
  133868296894800: TensorSpec(shape=(256,), dtype=tf.float32, name=None)
  133868295553488: TensorSpec(shape=(), dtype=tf.resource, name=None)
  133868296894416: TensorSpec(shape=(128,), dtype=tf.float32, name=None)
  133868296896144: TensorSpec(shape=(1, 1, 128, 128), dtype=tf.float32, name=None)
  133868295555408: TensorSpec(shape=(128,), dtype=tf.float32, name=None)
  133868295556752: TensorSpec(shape=(1, 1, 128, 256), dtype=tf.float32, name=None)
  133868295556560: TensorSpec(shape=(256,), dtype=tf.float32, name=None)
  133868295556368: TensorSpec(shape=(1, 1, 256, 128), dtype=tf.float32, name=None)
  133868295555792: TensorSpec(shape=(128,), dtype=tf.float32, name=None)
  133868295555216: TensorSpec(shape=(1, 1, 256, 256), dtype=tf.float32, name=None)
  133868295554448: TensorSpec(shape=(256,), dtype=tf.float32, name=None)
  133868295555600: TensorSpec(shape=(1, 1, 256, 1280), dtype=tf.float32, name=None)
  133868295555024: TensorSpec(shape=(1280,), dtype=tf.float32, name=None)
  133868295556944: TensorSpec(shape=(1280, 1000), dtype=tf.float32, name=None)
  133868295557520: TensorSpec(shape=(), dtype=tf.float32, name=None)
  133868295557136: TensorSpec(shape=(1000,), dtype=tf.float32, name=None)
TensorFlow SavedModel: export success ✅ 41.3s, saved as 'yolo11n-cls_saved_model' (27.0 MB)

TensorFlow Lite: starting export with tensorflow 2.20.0...
TensorFlow Lite: export success ✅ 0.0s, saved as 'yolo11n-cls_saved_model/yolo11n-cls_float32.tflite' (10.8 MB)

Export complete (41.5s)
Results saved to /content/drive/MyDrive/shrimp_disease_images/ShrimpDiseaseImageBD An Image Dataset for Computer Vision-Based Detection of Shrimp Diseases in Bangladesh/Root/Raw Images/Raw Images/yolo11n-cls_saved_model/yolo11n-cls_float32.tflite
Predict:         yolo predict task=classify model=yolo11n-cls_saved_model/yolo11n-cls_float32.tflite imgsz=224
Validate:        yolo val task=classify model=yolo11n-cls_saved_model/yolo11n-cls_float32.tflite imgsz=224 data=../datasets/imagenet
Visualize:       https://netron.app

,Target,Export Format,Export Path,Export Note
0,PyTorch mobilenet_v3_large,onnx,/content/drive/MyDrive/shrimp_disease_images/b...,TFLite failed: ModuleNotFoundError: No module ...
1,YOLO yolo11n-cls,tflite,yolo11n-cls_saved_model/yolo11n-cls_float32.tf...,

Export smoke tests passed. Continuing to baseline training.

================================================================================
Training PyTorch baseline: mobilenet_v3_large
================================================================================

Epoch 01/15 | Train Loss: 1.2355 - Acc: 0.4552 | Val Loss: 1.2708 - Macro F1: 0.4293
  --> Saved best checkpoint: macro F1 0.4293

Epoch 02/15 | Train Loss: 0.8227 - Acc: 0.6741 | Val Loss: 1.1726 - Macro F1: 0.4113
  --> No improvement (1/3)

Epoch 03/15 | Train Loss: 0.5199 - Acc: 0.8221 | Val Loss: 1.1862 - Macro F1: 0.2510
  --> No improvement (2/3)

Epoch 04/15 | Train Loss: 0.2882 - Acc: 0.9154 | Val Loss: 1.1565 - Macro F1: 0.3713
  --> No improvement (3/3)
  --> Early stopping triggered.
Recorded result:

,Model,Parameters (M),Training Time (s),Val F1-Score,Test Accuracy,Test F1-Score,Inference Time (s),FPS,Latency (ms),Export Format,Export Path,Export Note
0,mobilenet_v3_large,4.21,159.4,0.4293,0.4855,0.3906,6.14,28.2,35.51,onnx,/content/drive/MyDrive/shrimp_disease_images/b...,TFLite failed: ModuleNotFoundError: No module ...

================================================================================
Training PyTorch baseline: efficientnet_b0
================================================================================
Downloading: "https://download.pytorch.org/models/efficientnet_b0_rwightman-7f5810bc.pth" to /root/.cache/torch/hub/checkpoints/efficientnet_b0_rwightman-7f5810bc.pth

100%|██████████| 20.5M/20.5M [00:00<00:00, 114MB/s]

Epoch 01/15 | Train Loss: 1.2381 - Acc: 0.4950 | Val Loss: 1.1345 - Macro F1: 0.4593
  --> Saved best checkpoint: macro F1 0.4593

Epoch 02/15 | Train Loss: 0.9103 - Acc: 0.6480 | Val Loss: 0.8687 - Macro F1: 0.6142
  --> Saved best checkpoint: macro F1 0.6142

Epoch 03/15 | Train Loss: 0.7044 - Acc: 0.7512 | Val Loss: 0.7869 - Macro F1: 0.6058
  --> No improvement (1/3)

Epoch 04/15 | Train Loss: 0.5635 - Acc: 0.8221 | Val Loss: 0.6807 - Macro F1: 0.6931
  --> Saved best checkpoint: macro F1 0.6931

Epoch 05/15 | Train Loss: 0.4003 - Acc: 0.8794 | Val Loss: 0.6999 - Macro F1: 0.6815
  --> No improvement (1/3)

Epoch 06/15 | Train Loss: 0.3069 - Acc: 0.9117 | Val Loss: 0.6734 - Macro F1: 0.6824
  --> No improvement (2/3)

Epoch 07/15 | Train Loss: 0.2656 - Acc: 0.9241 | Val Loss: 0.6576 - Macro F1: 0.7072
  --> Saved best checkpoint: macro F1 0.7072

Epoch 08/15 | Train Loss: 0.1837 - Acc: 0.9540 | Val Loss: 0.6398 - Macro F1: 0.6981
  --> No improvement (1/3)

Epoch 09/15 | Train Loss: 0.1694 - Acc: 0.9527 | Val Loss: 0.6872 - Macro F1: 0.7450
  --> Saved best checkpoint: macro F1 0.7450

Epoch 10/15 | Train Loss: 0.1290 - Acc: 0.9677 | Val Loss: 0.6483 - Macro F1: 0.7782
  --> Saved best checkpoint: macro F1 0.7782

Epoch 11/15 | Train Loss: 0.0976 - Acc: 0.9726 | Val Loss: 0.5802 - Macro F1: 0.7734
  --> No improvement (1/3)

Epoch 12/15 | Train Loss: 0.0902 - Acc: 0.9826 | Val Loss: 0.6750 - Macro F1: 0.7778
  --> No improvement (2/3)

Epoch 13/15 | Train Loss: 0.0996 - Acc: 0.9776 | Val Loss: 0.6428 - Macro F1: 0.7699
  --> No improvement (3/3)
  --> Early stopping triggered.
Recorded result:

,Model,Parameters (M),Training Time (s),Val F1-Score,Test Accuracy,Test F1-Score,Inference Time (s),FPS,Latency (ms),Export Format,Export Path,Export Note
0,efficientnet_b0,4.01,512.4,0.7782,0.7399,0.7232,8.05,21.5,46.51,onnx,/content/drive/MyDrive/shrimp_disease_images/b...,TFLite failed: ModuleNotFoundError: No module ...

================================================================================
Training YOLO baseline: yolo11n-cls
================================================================================
Ultralytics 8.4.51 🚀 Python-3.12.13 torch-2.10.0+cu128 CUDA:0 (Tesla T4, 14913MiB)
engine/trainer: agnostic_nms=False, amp=True, angle=1.0, augment=False, auto_augment=randaugment, batch=32, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, cls_pw=0.0, compile=False, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=/content/drive/MyDrive/shrimp_disease_images/baseline_model_comparison/yolo_dataset, degrees=0.0, deterministic=True, device=0, dfl=1.5, dnn=False, dropout=0.0, dynamic=False, embed=None, end2end=None, epochs=15, erasing=0.4, exist_ok=True, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=None, half=False, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=224, int8=False, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolo11n-cls.pt, momentum=0.937, mosaic=1.0, multi_scale=0.0, name=yolo11n-cls, nbs=64, nms=False, opset=None, optimize=False, optimizer=auto, overlap_mask=True, patience=3, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=/content/drive/MyDrive/shrimp_disease_images/baseline_model_comparison/yolo_runs, rect=False, resume=False, retina_masks=False, rle=1.0, save=True, save_conf=False, save_crop=False, save_dir=/content/drive/MyDrive/shrimp_disease_images/baseline_model_comparison/yolo_runs/yolo11n-cls, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=42, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=classify, time=None, tracker=botsort.yaml, translate=0.1, val=True, verbose=True, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0005, workers=8, workspace=None
train: /content/drive/MyDrive/shrimp_disease_images/baseline_model_comparison/yolo_dataset/train... found 804 images in 4 classes ✅
val: /content/drive/MyDrive/shrimp_disease_images/baseline_model_comparison/yolo_dataset/val... found 172 images in 4 classes ✅
test: /content/drive/MyDrive/shrimp_disease_images/baseline_model_comparison/yolo_dataset/test... found 173 images in 4 classes ✅
Overriding model.yaml nc=80 with nc=4

                   from  n    params  module                                       arguments
  0                  -1  1       464  ultralytics.nn.modules.conv.Conv             [3, 16, 3, 2]
  1                  -1  1      4672  ultralytics.nn.modules.conv.Conv             [16, 32, 3, 2]
  2                  -1  1      6640  ultralytics.nn.modules.block.C3k2            [32, 64, 1, False, 0.25]
  3                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]
  4                  -1  1     26080  ultralytics.nn.modules.block.C3k2            [64, 128, 1, False, 0.25]
  5                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
  6                  -1  1     87040  ultralytics.nn.modules.block.C3k2            [128, 128, 1, True]
  7                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]
  8                  -1  1    346112  ultralytics.nn.modules.block.C3k2            [256, 256, 1, True]
  9                  -1  1    249728  ultralytics.nn.modules.block.C2PSA           [256, 256, 1]
 10                  -1  1    335364  ultralytics.nn.modules.head.Classify         [256, 4]
YOLO11n-cls summary: 86 layers, 1,536,228 parameters, 1,536,228 gradients, 3.3 GFLOPs
Transferred 234/236 items from pretrained weights
AMP: running Automatic Mixed Precision (AMP) checks...
Downloading https://github.com/ultralytics/assets/releases/download/v8.4.0/yolo26n.pt to 'yolo26n.pt': 100% ━━━━━━━━━━━━ 5.3MB 94.1MB/s 0.1s
AMP: checks passed ✅
train: Fast image access ✅ (ping: 3.9±7.3 ms, read: 34.1±27.7 MB/s, size: 119.3 KB)
train: Scanning /content/drive/MyDrive/shrimp_disease_images/baseline_model_comparison/yolo_dataset/train... 804 images, 0 corrupt: 100% ━━━━━━━━━━━━ 804/804 172.5it/s 4.7s
train: New cache created: /content/drive/MyDrive/shrimp_disease_images/baseline_model_comparison/yolo_dataset/train.cache
val: Fast image access ✅ (ping: 0.7±0.2 ms, read: 27.6±17.6 MB/s, size: 119.2 KB)
val: Scanning /content/drive/MyDrive/shrimp_disease_images/baseline_model_comparison/yolo_dataset/val... 172 images, 0 corrupt: 100% ━━━━━━━━━━━━ 172/172 93.0it/s 1.8s
val: New cache created: /content/drive/MyDrive/shrimp_disease_images/baseline_model_comparison/yolo_dataset/val.cache
optimizer: 'optimizer=auto' found, ignoring 'lr0=0.01' and 'momentum=0.937' and determining best 'optimizer', 'lr0' and 'momentum' automatically...
optimizer: AdamW(lr=0.00125, momentum=0.9) with parameter groups 39 weight(decay=0.0), 40 weight(decay=0.0005), 40 bias(decay=0.0)
Image sizes 224 train, 224 val
Using 2 dataloader workers
Logging results to /content/drive/MyDrive/shrimp_disease_images/baseline_model_comparison/yolo_runs/yolo11n-cls
Starting training for 15 epochs...

      Epoch    GPU_mem       loss  Instances       Size
Downloading https://ultralytics.com/assets/Arial.ttf to '/root/.config/Ultralytics/Arial.ttf': 100% ━━━━━━━━━━━━ 755.1KB 18.7MB/s 0.0s
       1/15     0.439G      1.301          4        224: 100% ━━━━━━━━━━━━ 26/26 2.3s/it 59.9s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 3/3 1.1s/it 3.2s
                   all      0.599          1

      Epoch    GPU_mem       loss  Instances       Size
       2/15     0.541G     0.9734          4        224: 100% ━━━━━━━━━━━━ 26/26 1.3s/it 32.9s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 3/3 50.8it/s 0.1s
                   all      0.657          1

      Epoch    GPU_mem       loss  Instances       Size
       3/15     0.543G     0.9054          4        224: 100% ━━━━━━━━━━━━ 26/26 1.6s/it 41.6s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 3/3 29.0it/s 0.1s
                   all      0.587          1

      Epoch    GPU_mem       loss  Instances       Size
       4/15     0.543G     0.8269          4        224: 100% ━━━━━━━━━━━━ 26/26 1.6s/it 41.3s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 3/3 24.2it/s 0.1s
                   all      0.657          1

      Epoch    GPU_mem       loss  Instances       Size
       5/15     0.543G     0.8525          4        224: 100% ━━━━━━━━━━━━ 26/26 1.6s/it 42.0s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 3/3 20.6it/s 0.1s
                   all       0.61          1
EarlyStopping: Training stopped early as no improvement observed in last 3 epochs. Best results observed at epoch 2, best model saved as best.pt.
To update EarlyStopping(patience=3) pass a new patience value, i.e. `patience=300` or use `patience=0` to disable EarlyStopping.

5 epochs completed in 0.063 hours.
Optimizer stripped from /content/drive/MyDrive/shrimp_disease_images/baseline_model_comparison/yolo_runs/yolo11n-cls/weights/last.pt, 3.2MB
Optimizer stripped from /content/drive/MyDrive/shrimp_disease_images/baseline_model_comparison/yolo_runs/yolo11n-cls/weights/best.pt, 3.2MB

Validating /content/drive/MyDrive/shrimp_disease_images/baseline_model_comparison/yolo_runs/yolo11n-cls/weights/best.pt...
Ultralytics 8.4.51 🚀 Python-3.12.13 torch-2.10.0+cu128 CUDA:0 (Tesla T4, 14913MiB)
YOLO11n-cls summary (fused): 47 layers, 1,531,148 parameters, 0 gradients, 3.2 GFLOPs
train: /content/drive/MyDrive/shrimp_disease_images/baseline_model_comparison/yolo_dataset/train... found 804 images in 4 classes ✅
val: /content/drive/MyDrive/shrimp_disease_images/baseline_model_comparison/yolo_dataset/val... found 172 images in 4 classes ✅
test: /content/drive/MyDrive/shrimp_disease_images/baseline_model_comparison/yolo_dataset/test... found 173 images in 4 classes ✅
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 3/3 12.9it/s 0.2s
                   all      0.657          1
Speed: 0.1ms preprocess, 0.8ms inference, 0.0ms loss, 0.0ms postprocess per image
Results saved to /content/drive/MyDrive/shrimp_disease_images/baseline_model_comparison/yolo_runs/yolo11n-cls
Ultralytics 8.4.51 🚀 Python-3.12.13 torch-2.10.0+cu128 CPU (Intel Xeon CPU @ 2.00GHz)

PyTorch: starting from '/content/drive/MyDrive/shrimp_disease_images/baseline_model_comparison/yolo_runs/yolo11n-cls/weights/best.pt' with input shape (1, 3, 224, 224) BCHW and output shape(s) (1, 4) (3.0 MB)

ONNX: starting export with onnx 1.21.0 opset 20...
ONNX: slimming with onnxslim 0.1.93...
ONNX: export success ✅ 1.0s, saved as '/content/drive/MyDrive/shrimp_disease_images/baseline_model_comparison/yolo_runs/yolo11n-cls/weights/best.onnx' (5.9 MB)

TensorFlow SavedModel: starting export with tensorflow 2.20.0...
TensorFlow SavedModel: starting TFLite export with onnx2tf 1.28.8...
Saved artifact at '/content/drive/MyDrive/shrimp_disease_images/baseline_model_comparison/yolo_runs/yolo11n-cls/weights/best_saved_model'. The following endpoints are available:

* Endpoint 'serving_default'
  inputs_0 (POSITIONAL_ONLY): TensorSpec(shape=(1, 224, 224, 3), dtype=tf.float32, name='images')
Output Type:
  TensorSpec(shape=(1, 4), dtype=tf.float32, name=None)
Captures:
  133868178783888: TensorSpec(shape=(4, 2), dtype=tf.int32, name=None)
  133868178783504: TensorSpec(shape=(3, 3, 3, 16), dtype=tf.float32, name=None)
  133868178781392: TensorSpec(shape=(16,), dtype=tf.float32, name=None)
  133868178783120: TensorSpec(shape=(4, 2), dtype=tf.int32, name=None)
  133868178776400: TensorSpec(shape=(3, 3, 16, 32), dtype=tf.float32, name=None)
  133868178780240: TensorSpec(shape=(32,), dtype=tf.float32, name=None)
  133868178782544: TensorSpec(shape=(1, 1, 32, 32), dtype=tf.float32, name=None)
  133868178782736: TensorSpec(shape=(32,), dtype=tf.float32, name=None)
  133868178781200: TensorSpec(shape=(4,), dtype=tf.int64, name=None)
  133868178782160: TensorSpec(shape=(4,), dtype=tf.int64, name=None)
  133868178779664: TensorSpec(shape=(3, 3, 16, 8), dtype=tf.float32, name=None)
  133868178779472: TensorSpec(shape=(8,), dtype=tf.float32, name=None)
  133868178781968: TensorSpec(shape=(3, 3, 8, 16), dtype=tf.float32, name=None)
  133868178783696: TensorSpec(shape=(16,), dtype=tf.float32, name=None)
  133868178777744: TensorSpec(shape=(4,), dtype=tf.int64, name=None)
  133868178780624: TensorSpec(shape=(4,), dtype=tf.int64, name=None)
  133868178779280: TensorSpec(shape=(1, 1, 48, 64), dtype=tf.float32, name=None)
  133868178777360: TensorSpec(shape=(64,), dtype=tf.float32, name=None)
  133868178781008: TensorSpec(shape=(4, 2), dtype=tf.int32, name=None)
  133868178780048: TensorSpec(shape=(3, 3, 64, 64), dtype=tf.float32, name=None)
  133868178780816: TensorSpec(shape=(64,), dtype=tf.float32, name=None)
  133868178778896: TensorSpec(shape=(1, 1, 64, 64), dtype=tf.float32, name=None)
  133868178778704: TensorSpec(shape=(64,), dtype=tf.float32, name=None)
  133868178778128: TensorSpec(shape=(4,), dtype=tf.int64, name=None)
  133868178778320: TensorSpec(shape=(4,), dtype=tf.int64, name=None)
  133868295559440: TensorSpec(shape=(3, 3, 32, 16), dtype=tf.float32, name=None)
  133868295560208: TensorSpec(shape=(16,), dtype=tf.float32, name=None)
  133868178776592: TensorSpec(shape=(3, 3, 16, 32), dtype=tf.float32, name=None)
  133868178779856: TensorSpec(shape=(32,), dtype=tf.float32, name=None)
  133868178777552: TensorSpec(shape=(4,), dtype=tf.int64, name=None)
  133868178776784: TensorSpec(shape=(4,), dtype=tf.int64, name=None)
  133868178777936: TensorSpec(shape=(1, 1, 96, 128), dtype=tf.float32, name=None)
  133868178778512: TensorSpec(shape=(128,), dtype=tf.float32, name=None)
  133868178775248: TensorSpec(shape=(4, 2), dtype=tf.int32, name=None)
  133868178780432: TensorSpec(shape=(3, 3, 128, 128), dtype=tf.float32, name=None)
  133867725095184: TensorSpec(shape=(128,), dtype=tf.float32, name=None)
  133867725095376: TensorSpec(shape=(1, 1, 128, 128), dtype=tf.float32, name=None)
  133867725095568: TensorSpec(shape=(128,), dtype=tf.float32, name=None)
  133867725096144: TensorSpec(shape=(4,), dtype=tf.int64, name=None)
  133867725095952: TensorSpec(shape=(4,), dtype=tf.int64, name=None)
  133867725098064: TensorSpec(shape=(1, 1, 64, 32), dtype=tf.float32, name=None)
  133867725098256: TensorSpec(shape=(32,), dtype=tf.float32, name=None)
  133867725097488: TensorSpec(shape=(3, 3, 32, 32), dtype=tf.float32, name=None)
  133867725098448: TensorSpec(shape=(32,), dtype=tf.float32, name=None)
  133867725098640: TensorSpec(shape=(3, 3, 32, 32), dtype=tf.float32, name=None)
  133867725098832: TensorSpec(shape=(32,), dtype=tf.float32, name=None)
  133867725097680: TensorSpec(shape=(3, 3, 32, 32), dtype=tf.float32, name=None)
  133867725099216: TensorSpec(shape=(32,), dtype=tf.float32, name=None)
  133867725097104: TensorSpec(shape=(3, 3, 32, 32), dtype=tf.float32, name=None)
  133867725094992: TensorSpec(shape=(1, 1, 64, 32), dtype=tf.float32, name=None)
  133867725099408: TensorSpec(shape=(32,), dtype=tf.float32, name=None)
  133867725095760: TensorSpec(shape=(32,), dtype=tf.float32, name=None)
  133867725099984: TensorSpec(shape=(1, 1, 64, 64), dtype=tf.float32, name=None)
  133867725099024: TensorSpec(shape=(64,), dtype=tf.float32, name=None)
  133867725096336: TensorSpec(shape=(4,), dtype=tf.int64, name=None)
  133867725096528: TensorSpec(shape=(4,), dtype=tf.int64, name=None)
  133867725100176: TensorSpec(shape=(1, 1, 192, 128), dtype=tf.float32, name=None)
  133867725100368: TensorSpec(shape=(128,), dtype=tf.float32, name=None)
  133867725100560: TensorSpec(shape=(4, 2), dtype=tf.int32, name=None)
  133867725099600: TensorSpec(shape=(3, 3, 128, 256), dtype=tf.float32, name=None)
  133867725099792: TensorSpec(shape=(256,), dtype=tf.float32, name=None)
  133867725100944: TensorSpec(shape=(1, 1, 256, 256), dtype=tf.float32, name=None)
  133867725101136: TensorSpec(shape=(256,), dtype=tf.float32, name=None)
  133867725101712: TensorSpec(shape=(4,), dtype=tf.int64, name=None)
  133867725101520: TensorSpec(shape=(4,), dtype=tf.int64, name=None)
  133867725103632: TensorSpec(shape=(1, 1, 128, 64), dtype=tf.float32, name=None)
  133867725103824: TensorSpec(shape=(64,), dtype=tf.float32, name=None)
  133867725103056: TensorSpec(shape=(3, 3, 64, 64), dtype=tf.float32, name=None)
  133867725104016: TensorSpec(shape=(64,), dtype=tf.float32, name=None)
  133867725104208: TensorSpec(shape=(3, 3, 64, 64), dtype=tf.float32, name=None)
  133867725104400: TensorSpec(shape=(64,), dtype=tf.float32, name=None)
  133867725103248: TensorSpec(shape=(3, 3, 64, 64), dtype=tf.float32, name=None)
  133867725104784: TensorSpec(shape=(64,), dtype=tf.float32, name=None)
  133867725102672: TensorSpec(shape=(3, 3, 64, 64), dtype=tf.float32, name=None)
  133867725100752: TensorSpec(shape=(1, 1, 128, 64), dtype=tf.float32, name=None)
  133867725104976: TensorSpec(shape=(64,), dtype=tf.float32, name=None)
  133867725101328: TensorSpec(shape=(64,), dtype=tf.float32, name=None)
  133867725105552: TensorSpec(shape=(1, 1, 128, 128), dtype=tf.float32, name=None)
  133867725104592: TensorSpec(shape=(128,), dtype=tf.float32, name=None)
  133867725101904: TensorSpec(shape=(4,), dtype=tf.int64, name=None)
  133867725102096: TensorSpec(shape=(4,), dtype=tf.int64, name=None)
  133867725105744: TensorSpec(shape=(1, 1, 384, 256), dtype=tf.float32, name=None)
  133867725105936: TensorSpec(shape=(256,), dtype=tf.float32, name=None)
  133867725105168: TensorSpec(shape=(1, 1, 256, 256), dtype=tf.float32, name=None)
  133867725106128: TensorSpec(shape=(256,), dtype=tf.float32, name=None)
  133867725106512: TensorSpec(shape=(1, 1, 128, 256), dtype=tf.float32, name=None)
  133867725105360: TensorSpec(shape=(256,), dtype=tf.float32, name=None)
  133867725107088: TensorSpec(shape=(), dtype=tf.resource, name=None)
  133867725108240: TensorSpec(shape=(128,), dtype=tf.float32, name=None)
  133867725108432: TensorSpec(shape=(1, 1, 128, 128), dtype=tf.float32, name=None)
  133867725109200: TensorSpec(shape=(128,), dtype=tf.float32, name=None)
  133867725109584: TensorSpec(shape=(1, 1, 128, 256), dtype=tf.float32, name=None)
  133867725107472: TensorSpec(shape=(256,), dtype=tf.float32, name=None)
  133867725107280: TensorSpec(shape=(1, 1, 256, 128), dtype=tf.float32, name=None)
  133867725107856: TensorSpec(shape=(128,), dtype=tf.float32, name=None)
  133867725109392: TensorSpec(shape=(1, 1, 256, 256), dtype=tf.float32, name=None)
  133867725108816: TensorSpec(shape=(256,), dtype=tf.float32, name=None)
  133867725109008: TensorSpec(shape=(1, 1, 256, 1280), dtype=tf.float32, name=None)
  133867725107664: TensorSpec(shape=(1280,), dtype=tf.float32, name=None)
  133867725106704: TensorSpec(shape=(1280, 4), dtype=tf.float32, name=None)
  133867725108048: TensorSpec(shape=(), dtype=tf.float32, name=None)
  133867725109968: TensorSpec(shape=(4,), dtype=tf.float32, name=None)
TensorFlow SavedModel: export success ✅ 6.7s, saved as '/content/drive/MyDrive/shrimp_disease_images/baseline_model_comparison/yolo_runs/yolo11n-cls/weights/best_saved_model' (14.8 MB)

TensorFlow Lite: starting export with tensorflow 2.20.0...
TensorFlow Lite: export success ✅ 0.0s, saved as '/content/drive/MyDrive/shrimp_disease_images/baseline_model_comparison/yolo_runs/yolo11n-cls/weights/best_saved_model/best_float32.tflite' (5.9 MB)

Export complete (6.7s)
Results saved to /content/drive/MyDrive/shrimp_disease_images/baseline_model_comparison/yolo_runs/yolo11n-cls/weights/best_saved_model/best_float32.tflite
Predict:         yolo predict task=classify model=/content/drive/MyDrive/shrimp_disease_images/baseline_model_comparison/yolo_runs/yolo11n-cls/weights/best_saved_model/best_float32.tflite imgsz=224
Validate:        yolo val task=classify model=/content/drive/MyDrive/shrimp_disease_images/baseline_model_comparison/yolo_runs/yolo11n-cls/weights/best_saved_model/best_float32.tflite imgsz=224 data=/content/drive/MyDrive/shrimp_disease_images/baseline_model_comparison/yolo_dataset
Visualize:       https://netron.app
Recorded result:

,Model,Parameters (M),Training Time (s),Val F1-Score,Test Accuracy,Test F1-Score,Inference Time (s),FPS,Latency (ms),Export Format,Export Path,Export Note
0,yolo11n-cls,1.53,253.0,0.636,0.6416,0.6226,17.79,9.7,102.84,tflite,/content/drive/MyDrive/shrimp_disease_images/b...,

================================================================================
Training YOLO baseline: yolo11m-cls
================================================================================
Downloading https://github.com/ultralytics/assets/releases/download/v8.4.0/yolo11m-cls.pt to 'yolo11m-cls.pt': 100% ━━━━━━━━━━━━ 22.4MB 85.6MB/s 0.3s
Ultralytics 8.4.51 🚀 Python-3.12.13 torch-2.10.0+cu128 CUDA:0 (Tesla T4, 14913MiB)
engine/trainer: agnostic_nms=False, amp=True, angle=1.0, augment=False, auto_augment=randaugment, batch=32, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, cls_pw=0.0, compile=False, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=/content/drive/MyDrive/shrimp_disease_images/baseline_model_comparison/yolo_dataset, degrees=0.0, deterministic=True, device=0, dfl=1.5, dnn=False, dropout=0.0, dynamic=False, embed=None, end2end=None, epochs=15, erasing=0.4, exist_ok=True, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=None, half=False, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=224, int8=False, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolo11m-cls.pt, momentum=0.937, mosaic=1.0, multi_scale=0.0, name=yolo11m-cls, nbs=64, nms=False, opset=None, optimize=False, optimizer=auto, overlap_mask=True, patience=3, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=/content/drive/MyDrive/shrimp_disease_images/baseline_model_comparison/yolo_runs, rect=False, resume=False, retina_masks=False, rle=1.0, save=True, save_conf=False, save_crop=False, save_dir=/content/drive/MyDrive/shrimp_disease_images/baseline_model_comparison/yolo_runs/yolo11m-cls, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=42, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=classify, time=None, tracker=botsort.yaml, translate=0.1, val=True, verbose=True, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0005, workers=8, workspace=None
train: /content/drive/MyDrive/shrimp_disease_images/baseline_model_comparison/yolo_dataset/train... found 804 images in 4 classes ✅
val: /content/drive/MyDrive/shrimp_disease_images/baseline_model_comparison/yolo_dataset/val... found 172 images in 4 classes ✅
test: /content/drive/MyDrive/shrimp_disease_images/baseline_model_comparison/yolo_dataset/test... found 173 images in 4 classes ✅
Overriding model.yaml nc=80 with nc=4

                   from  n    params  module                                       arguments
  0                  -1  1      1856  ultralytics.nn.modules.conv.Conv             [3, 64, 3, 2]
  1                  -1  1     73984  ultralytics.nn.modules.conv.Conv             [64, 128, 3, 2]
  2                  -1  1    111872  ultralytics.nn.modules.block.C3k2            [128, 256, 1, True, 0.25]
  3                  -1  1    590336  ultralytics.nn.modules.conv.Conv             [256, 256, 3, 2]
  4                  -1  1    444928  ultralytics.nn.modules.block.C3k2            [256, 512, 1, True, 0.25]
  5                  -1  1   2360320  ultralytics.nn.modules.conv.Conv             [512, 512, 3, 2]
  6                  -1  1   1380352  ultralytics.nn.modules.block.C3k2            [512, 512, 1, True]
  7                  -1  1   2360320  ultralytics.nn.modules.conv.Conv             [512, 512, 3, 2]
  8                  -1  1   1380352  ultralytics.nn.modules.block.C3k2            [512, 512, 1, True]
  9                  -1  1    990976  ultralytics.nn.modules.block.C2PSA           [512, 512, 1]
 10                  -1  1    663044  ultralytics.nn.modules.head.Classify         [512, 4]
YOLO11m-cls summary: 106 layers, 10,358,340 parameters, 10,358,340 gradients, 39.6 GFLOPs
Transferred 294/296 items from pretrained weights
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: checks passed ✅
train: Fast image access ✅ (ping: 1.1±1.0 ms, read: 38.9±30.4 MB/s, size: 119.3 KB)
train: Scanning /content/drive/MyDrive/shrimp_disease_images/baseline_model_comparison/yolo_dataset/train... 804 images, 0 corrupt: 100% ━━━━━━━━━━━━ 804/804 153.3Mit/s 0.0s
val: Fast image access ✅ (ping: 3.6±1.7 ms, read: 12.5±3.6 MB/s, size: 119.2 KB)
val: Scanning /content/drive/MyDrive/shrimp_disease_images/baseline_model_comparison/yolo_dataset/val... 172 images, 0 corrupt: 100% ━━━━━━━━━━━━ 172/172 8.9Mit/s 0.0s
optimizer: 'optimizer=auto' found, ignoring 'lr0=0.01' and 'momentum=0.937' and determining best 'optimizer', 'lr0' and 'momentum' automatically...
optimizer: AdamW(lr=0.00125, momentum=0.9) with parameter groups 49 weight(decay=0.0), 50 weight(decay=0.0005), 50 bias(decay=0.0)
Image sizes 224 train, 224 val
Using 2 dataloader workers
Logging results to /content/drive/MyDrive/shrimp_disease_images/baseline_model_comparison/yolo_runs/yolo11m-cls
Starting training for 15 epochs...

      Epoch    GPU_mem       loss  Instances       Size
       1/15      1.42G      1.219          4        224: 100% ━━━━━━━━━━━━ 26/26 2.4s/it 1:01
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 3/3 1.2s/it 3.6s
                   all      0.634          1

      Epoch    GPU_mem       loss  Instances       Size
       2/15      1.77G     0.9949          4        224: 100% ━━━━━━━━━━━━ 26/26 1.5s/it 37.9s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 3/3 12.1it/s 0.2s
                   all      0.483          1

      Epoch    GPU_mem       loss  Instances       Size
       3/15      1.77G     0.9503          4        224: 100% ━━━━━━━━━━━━ 26/26 1.6s/it 42.1s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 3/3 12.6it/s 0.2s
                   all      0.424          1

      Epoch    GPU_mem       loss  Instances       Size
       4/15      1.77G     0.9769          4        224: 100% ━━━━━━━━━━━━ 26/26 1.6s/it 41.9s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 3/3 15.4it/s 0.2s
                   all      0.576          1
EarlyStopping: Training stopped early as no improvement observed in last 3 epochs. Best results observed at epoch 1, best model saved as best.pt.
To update EarlyStopping(patience=3) pass a new patience value, i.e. `patience=300` or use `patience=0` to disable EarlyStopping.

4 epochs completed in 0.055 hours.
Optimizer stripped from /content/drive/MyDrive/shrimp_disease_images/baseline_model_comparison/yolo_runs/yolo11m-cls/weights/last.pt, 20.9MB
Optimizer stripped from /content/drive/MyDrive/shrimp_disease_images/baseline_model_comparison/yolo_runs/yolo11m-cls/weights/best.pt, 20.9MB

Validating /content/drive/MyDrive/shrimp_disease_images/baseline_model_comparison/yolo_runs/yolo11m-cls/weights/best.pt...
Ultralytics 8.4.51 🚀 Python-3.12.13 torch-2.10.0+cu128 CUDA:0 (Tesla T4, 14913MiB)
YOLO11m-cls summary (fused): 57 layers, 10,346,756 parameters, 0 gradients, 39.3 GFLOPs
train: /content/drive/MyDrive/shrimp_disease_images/baseline_model_comparison/yolo_dataset/train... found 804 images in 4 classes ✅
val: /content/drive/MyDrive/shrimp_disease_images/baseline_model_comparison/yolo_dataset/val... found 172 images in 4 classes ✅
test: /content/drive/MyDrive/shrimp_disease_images/baseline_model_comparison/yolo_dataset/test... found 173 images in 4 classes ✅
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 3/3 9.4it/s 0.3s
                   all      0.634          1
Speed: 0.1ms preprocess, 1.3ms inference, 0.0ms loss, 0.0ms postprocess per image
Results saved to /content/drive/MyDrive/shrimp_disease_images/baseline_model_comparison/yolo_runs/yolo11m-cls
Ultralytics 8.4.51 🚀 Python-3.12.13 torch-2.10.0+cu128 CPU (Intel Xeon CPU @ 2.00GHz)

PyTorch: starting from '/content/drive/MyDrive/shrimp_disease_images/baseline_model_comparison/yolo_runs/yolo11m-cls/weights/best.pt' with input shape (1, 3, 224, 224) BCHW and output shape(s) (1, 4) (19.9 MB)

ONNX: starting export with onnx 1.21.0 opset 20...
ONNX: slimming with onnxslim 0.1.93...
ONNX: export success ✅ 2.6s, saved as '/content/drive/MyDrive/shrimp_disease_images/baseline_model_comparison/yolo_runs/yolo11m-cls/weights/best.onnx' (39.5 MB)

TensorFlow SavedModel: starting export with tensorflow 2.20.0...
TensorFlow SavedModel: starting TFLite export with onnx2tf 1.28.8...
Saved artifact at '/content/drive/MyDrive/shrimp_disease_images/baseline_model_comparison/yolo_runs/yolo11m-cls/weights/best_saved_model'. The following endpoints are available:

* Endpoint 'serving_default'
  inputs_0 (POSITIONAL_ONLY): TensorSpec(shape=(1, 224, 224, 3), dtype=tf.float32, name='images')
Output Type:
  TensorSpec(shape=(1, 4), dtype=tf.float32, name=None)
Captures:
  133868178782160: TensorSpec(shape=(4, 2), dtype=tf.int32, name=None)
  133868178781200: TensorSpec(shape=(3, 3, 3, 64), dtype=tf.float32, name=None)
  133868178776592: TensorSpec(shape=(64,), dtype=tf.float32, name=None)
  133868178783696: TensorSpec(shape=(4, 2), dtype=tf.int32, name=None)
  133868178779472: TensorSpec(shape=(3, 3, 64, 128), dtype=tf.float32, name=None)
  133868178783504: TensorSpec(shape=(128,), dtype=tf.float32, name=None)
  133868178779664: TensorSpec(shape=(1, 1, 128, 128), dtype=tf.float32, name=None)
  133868178781968: TensorSpec(shape=(128,), dtype=tf.float32, name=None)
  133868178783120: TensorSpec(shape=(4,), dtype=tf.int64, name=None)
  133868178777360: TensorSpec(shape=(4,), dtype=tf.int64, name=None)
  133868178774288: TensorSpec(shape=(1, 1, 64, 32), dtype=tf.float32, name=None)
  133868178774096: TensorSpec(shape=(32,), dtype=tf.float32, name=None)
  133868178774672: TensorSpec(shape=(3, 3, 32, 32), dtype=tf.float32, name=None)
  133868178770640: TensorSpec(shape=(32,), dtype=tf.float32, name=None)
  133868178775824: TensorSpec(shape=(3, 3, 32, 32), dtype=tf.float32, name=None)
  133868178772560: TensorSpec(shape=(32,), dtype=tf.float32, name=None)
  133868178781392: TensorSpec(shape=(3, 3, 32, 32), dtype=tf.float32, name=None)
  133867725110544: TensorSpec(shape=(32,), dtype=tf.float32, name=None)
  133867725110352: TensorSpec(shape=(3, 3, 32, 32), dtype=tf.float32, name=None)
  133868178778704: TensorSpec(shape=(1, 1, 64, 32), dtype=tf.float32, name=None)
  133867725110160: TensorSpec(shape=(32,), dtype=tf.float32, name=None)
  133868178777744: TensorSpec(shape=(32,), dtype=tf.float32, name=None)
  133867725097872: TensorSpec(shape=(1, 1, 64, 64), dtype=tf.float32, name=None)
  133867725109776: TensorSpec(shape=(64,), dtype=tf.float32, name=None)
  133868178776400: TensorSpec(shape=(4,), dtype=tf.int64, name=None)
  133868178773904: TensorSpec(shape=(4,), dtype=tf.int64, name=None)
  133867725096912: TensorSpec(shape=(1, 1, 192, 256), dtype=tf.float32, name=None)
  133867725102288: TensorSpec(shape=(256,), dtype=tf.float32, name=None)
  133867725102864: TensorSpec(shape=(4, 2), dtype=tf.int32, name=None)
  133867725096720: TensorSpec(shape=(3, 3, 256, 256), dtype=tf.float32, name=None)
  133867725097296: TensorSpec(shape=(256,), dtype=tf.float32, name=None)
  133867725102480: TensorSpec(shape=(1, 1, 256, 256), dtype=tf.float32, name=None)
  133867725106896: TensorSpec(shape=(256,), dtype=tf.float32, name=None)
  133867725106704: TensorSpec(shape=(4,), dtype=tf.int64, name=None)
  133867725108048: TensorSpec(shape=(4,), dtype=tf.int64, name=None)
  133867725108432: TensorSpec(shape=(1, 1, 128, 64), dtype=tf.float32, name=None)
  133867725108240: TensorSpec(shape=(64,), dtype=tf.float32, name=None)
  133867725107472: TensorSpec(shape=(3, 3, 64, 64), dtype=tf.float32, name=None)
  133867725107088: TensorSpec(shape=(64,), dtype=tf.float32, name=None)
  133867725105360: TensorSpec(shape=(3, 3, 64, 64), dtype=tf.float32, name=None)
  133867725106512: TensorSpec(shape=(64,), dtype=tf.float32, name=None)
  133867725109584: TensorSpec(shape=(3, 3, 64, 64), dtype=tf.float32, name=None)
  133867725105168: TensorSpec(shape=(64,), dtype=tf.float32, name=None)
  133867725107856: TensorSpec(shape=(3, 3, 64, 64), dtype=tf.float32, name=None)
  133867725103440: TensorSpec(shape=(1, 1, 128, 64), dtype=tf.float32, name=None)
  133867725105936: TensorSpec(shape=(64,), dtype=tf.float32, name=None)
  133867725109968: TensorSpec(shape=(64,), dtype=tf.float32, name=None)
  133867725101904: TensorSpec(shape=(1, 1, 128, 128), dtype=tf.float32, name=None)
  133867725106128: TensorSpec(shape=(128,), dtype=tf.float32, name=None)
  133867725107664: TensorSpec(shape=(4,), dtype=tf.int64, name=None)
  133867725109008: TensorSpec(shape=(4,), dtype=tf.int64, name=None)
  133867725104592: TensorSpec(shape=(1, 1, 384, 512), dtype=tf.float32, name=None)
  133867725105552: TensorSpec(shape=(512,), dtype=tf.float32, name=None)
  133867725101328: TensorSpec(shape=(4, 2), dtype=tf.int32, name=None)
  133867725105744: TensorSpec(shape=(3, 3, 512, 512), dtype=tf.float32, name=None)
  133867725102096: TensorSpec(shape=(512,), dtype=tf.float32, name=None)
  133867725100752: TensorSpec(shape=(1, 1, 512, 512), dtype=tf.float32, name=None)
  133867725102672: TensorSpec(shape=(512,), dtype=tf.float32, name=None)
  133867725104400: TensorSpec(shape=(4,), dtype=tf.int64, name=None)
  133867725103248: TensorSpec(shape=(4,), dtype=tf.int64, name=None)
  133867725099792: TensorSpec(shape=(1, 1, 256, 128), dtype=tf.float32, name=None)
  133867725099600: TensorSpec(shape=(128,), dtype=tf.float32, name=None)
  133867725101712: TensorSpec(shape=(3, 3, 128, 128), dtype=tf.float32, name=None)
  133867725100560: TensorSpec(shape=(128,), dtype=tf.float32, name=None)
  133867725100368: TensorSpec(shape=(3, 3, 128, 128), dtype=tf.float32, name=None)
  133867725100176: TensorSpec(shape=(128,), dtype=tf.float32, name=None)
  133867725101136: TensorSpec(shape=(3, 3, 128, 128), dtype=tf.float32, name=None)
  133867725096336: TensorSpec(shape=(128,), dtype=tf.float32, name=None)
  133867725103632: TensorSpec(shape=(3, 3, 128, 128), dtype=tf.float32, name=None)
  133867725104976: TensorSpec(shape=(1, 1, 256, 128), dtype=tf.float32, name=None)
  133867725099024: TensorSpec(shape=(128,), dtype=tf.float32, name=None)
  133867725104784: TensorSpec(shape=(128,), dtype=tf.float32, name=None)
  133867725099408: TensorSpec(shape=(1, 1, 256, 256), dtype=tf.float32, name=None)
  133867725096528: TensorSpec(shape=(256,), dtype=tf.float32, name=None)
  133867725104208: TensorSpec(shape=(4,), dtype=tf.int64, name=None)
  133867725104016: TensorSpec(shape=(4,), dtype=tf.int64, name=None)
  133867725094992: TensorSpec(shape=(1, 1, 768, 512), dtype=tf.float32, name=None)
  133867725097104: TensorSpec(shape=(512,), dtype=tf.float32, name=None)
  133867725099216: TensorSpec(shape=(4, 2), dtype=tf.int32, name=None)
  133867725099984: TensorSpec(shape=(3, 3, 512, 512), dtype=tf.float32, name=None)
  133867725095760: TensorSpec(shape=(512,), dtype=tf.float32, name=None)
  133867725098832: TensorSpec(shape=(1, 1, 512, 512), dtype=tf.float32, name=None)
  133867725098640: TensorSpec(shape=(512,), dtype=tf.float32, name=None)
  133867725098256: TensorSpec(shape=(4,), dtype=tf.int64, name=None)
  133867725097488: TensorSpec(shape=(4,), dtype=tf.int64, name=None)
  133867725110928: TensorSpec(shape=(1, 1, 256, 128), dtype=tf.float32, name=None)
  133867725106320: TensorSpec(shape=(128,), dtype=tf.float32, name=None)
  133867725108624: TensorSpec(shape=(3, 3, 128, 128), dtype=tf.float32, name=None)
  133867725110736: TensorSpec(shape=(128,), dtype=tf.float32, name=None)
  133867725095376: TensorSpec(shape=(3, 3, 128, 128), dtype=tf.float32, name=None)
  133868295569232: TensorSpec(shape=(128,), dtype=tf.float32, name=None)
  133868295560208: TensorSpec(shape=(3, 3, 128, 128), dtype=tf.float32, name=None)
  133868295562128: TensorSpec(shape=(128,), dtype=tf.float32, name=None)
  133868295568464: TensorSpec(shape=(3, 3, 128, 128), dtype=tf.float32, name=None)
  133867725097680: TensorSpec(shape=(1, 1, 256, 128), dtype=tf.float32, name=None)
  133868295559056: TensorSpec(shape=(128,), dtype=tf.float32, name=None)
  133867725098448: TensorSpec(shape=(128,), dtype=tf.float32, name=None)
  133868295560592: TensorSpec(shape=(1, 1, 256, 256), dtype=tf.float32, name=None)
  133868295560016: TensorSpec(shape=(256,), dtype=tf.float32, name=None)
  133867725098064: TensorSpec(shape=(4,), dtype=tf.int64, name=None)
  133867725095952: TensorSpec(shape=(4,), dtype=tf.int64, name=None)
  133868295566928: TensorSpec(shape=(1, 1, 768, 512), dtype=tf.float32, name=None)
  133868295566544: TensorSpec(shape=(512,), dtype=tf.float32, name=None)
  133868295558672: TensorSpec(shape=(1, 1, 512, 512), dtype=tf.float32, name=None)
  133868295561168: TensorSpec(shape=(512,), dtype=tf.float32, name=None)
  133868295555792: TensorSpec(shape=(1, 1, 256, 512), dtype=tf.float32, name=None)
  133868295568272: TensorSpec(shape=(512,), dtype=tf.float32, name=None)
  133867685380944: TensorSpec(shape=(), dtype=tf.resource, name=None)
  133867685380368: TensorSpec(shape=(256,), dtype=tf.float32, name=None)
  133868295566160: TensorSpec(shape=(1, 1, 256, 256), dtype=tf.float32, name=None)
  133867685381520: TensorSpec(shape=(256,), dtype=tf.float32, name=None)
  133867685381712: TensorSpec(shape=(1, 1, 256, 512), dtype=tf.float32, name=None)
  133867685382864: TensorSpec(shape=(512,), dtype=tf.float32, name=None)
  133867685382288: TensorSpec(shape=(1, 1, 512, 256), dtype=tf.float32, name=None)
  133867685381904: TensorSpec(shape=(256,), dtype=tf.float32, name=None)
  133867685383056: TensorSpec(shape=(1, 1, 512, 512), dtype=tf.float32, name=None)
  133867685382480: TensorSpec(shape=(512,), dtype=tf.float32, name=None)
  133867685381328: TensorSpec(shape=(1, 1, 512, 1280), dtype=tf.float32, name=None)
  133867685382096: TensorSpec(shape=(1280,), dtype=tf.float32, name=None)
  133867685382672: TensorSpec(shape=(1280, 4), dtype=tf.float32, name=None)
  133867685383440: TensorSpec(shape=(), dtype=tf.float32, name=None)
  133867685383248: TensorSpec(shape=(4,), dtype=tf.float32, name=None)
TensorFlow SavedModel: export success ✅ 14.2s, saved as '/content/drive/MyDrive/shrimp_disease_images/baseline_model_comparison/yolo_runs/yolo11m-cls/weights/best_saved_model' (98.9 MB)

TensorFlow Lite: starting export with tensorflow 2.20.0...
TensorFlow Lite: export success ✅ 0.0s, saved as '/content/drive/MyDrive/shrimp_disease_images/baseline_model_comparison/yolo_runs/yolo11m-cls/weights/best_saved_model/best_float32.tflite' (39.5 MB)

Export complete (14.5s)
Results saved to /content/drive/MyDrive/shrimp_disease_images/baseline_model_comparison/yolo_runs/yolo11m-cls/weights/best_saved_model/best_float32.tflite
Predict:         yolo predict task=classify model=/content/drive/MyDrive/shrimp_disease_images/baseline_model_comparison/yolo_runs/yolo11m-cls/weights/best_saved_model/best_float32.tflite imgsz=224
Validate:        yolo val task=classify model=/content/drive/MyDrive/shrimp_disease_images/baseline_model_comparison/yolo_runs/yolo11m-cls/weights/best_saved_model/best_float32.tflite imgsz=224 data=/content/drive/MyDrive/shrimp_disease_images/baseline_model_comparison/yolo_dataset
Visualize:       https://netron.app
Recorded result:

,Model,Parameters (M),Training Time (s),Val F1-Score,Test Accuracy,Test F1-Score,Inference Time (s),FPS,Latency (ms),Export Format,Export Path,Export Note
0,yolo11m-cls,10.35,216.5,0.5309,0.659,0.56,16.08,10.8,92.94,tflite,/content/drive/MyDrive/shrimp_disease_images/b...,

================================================================================
Training YOLO baseline: yolo26n-cls
================================================================================
Downloading https://github.com/ultralytics/assets/releases/download/v8.4.0/yolo26n-cls.pt to 'yolo26n-cls.pt': 100% ━━━━━━━━━━━━ 5.5MB 84.0MB/s 0.1s
Ultralytics 8.4.51 🚀 Python-3.12.13 torch-2.10.0+cu128 CUDA:0 (Tesla T4, 14913MiB)
engine/trainer: agnostic_nms=False, amp=True, angle=1.0, augment=False, auto_augment=randaugment, batch=32, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, cls_pw=0.0, compile=False, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=/content/drive/MyDrive/shrimp_disease_images/baseline_model_comparison/yolo_dataset, degrees=0.0, deterministic=True, device=0, dfl=1.5, dnn=False, dropout=0.0, dynamic=False, embed=None, end2end=None, epochs=15, erasing=0.4, exist_ok=True, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=None, half=False, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=224, int8=False, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolo26n-cls.pt, momentum=0.937, mosaic=1.0, multi_scale=0.0, name=yolo26n-cls, nbs=64, nms=False, opset=None, optimize=False, optimizer=auto, overlap_mask=True, patience=3, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=/content/drive/MyDrive/shrimp_disease_images/baseline_model_comparison/yolo_runs, rect=False, resume=False, retina_masks=False, rle=1.0, save=True, save_conf=False, save_crop=False, save_dir=/content/drive/MyDrive/shrimp_disease_images/baseline_model_comparison/yolo_runs/yolo26n-cls, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=42, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=classify, time=None, tracker=botsort.yaml, translate=0.1, val=True, verbose=True, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0005, workers=8, workspace=None
train: /content/drive/MyDrive/shrimp_disease_images/baseline_model_comparison/yolo_dataset/train... found 804 images in 4 classes ✅
val: /content/drive/MyDrive/shrimp_disease_images/baseline_model_comparison/yolo_dataset/val... found 172 images in 4 classes ✅
test: /content/drive/MyDrive/shrimp_disease_images/baseline_model_comparison/yolo_dataset/test... found 173 images in 4 classes ✅
Overriding model.yaml nc=1000 with nc=4

                   from  n    params  module                                       arguments
  0                  -1  1       464  ultralytics.nn.modules.conv.Conv             [3, 16, 3, 2]
  1                  -1  1      4672  ultralytics.nn.modules.conv.Conv             [16, 32, 3, 2]
  2                  -1  1      6640  ultralytics.nn.modules.block.C3k2            [32, 64, 1, False, 0.25]
  3                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]
  4                  -1  1     26080  ultralytics.nn.modules.block.C3k2            [64, 128, 1, False, 0.25]
  5                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
  6                  -1  1     87040  ultralytics.nn.modules.block.C3k2            [128, 128, 1, True]
  7                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]
  8                  -1  1    346112  ultralytics.nn.modules.block.C3k2            [256, 256, 1, True]
  9                  -1  1    249728  ultralytics.nn.modules.block.C2PSA           [256, 256, 1]
 10                  -1  1    335364  ultralytics.nn.modules.head.Classify         [256, 4]
YOLO26n-cls summary: 86 layers, 1,536,228 parameters, 1,536,228 gradients, 3.3 GFLOPs
Transferred 234/236 items from pretrained weights
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: checks passed ✅
train: Fast image access ✅ (ping: 2.7±1.5 ms, read: 12.5±3.2 MB/s, size: 119.3 KB)
train: Scanning /content/drive/MyDrive/shrimp_disease_images/baseline_model_comparison/yolo_dataset/train... 804 images, 0 corrupt: 100% ━━━━━━━━━━━━ 804/804 198.4Mit/s 0.0s
val: Fast image access ✅ (ping: 1.0±1.0 ms, read: 28.5±16.8 MB/s, size: 119.2 KB)
val: Scanning /content/drive/MyDrive/shrimp_disease_images/baseline_model_comparison/yolo_dataset/val... 172 images, 0 corrupt: 100% ━━━━━━━━━━━━ 172/172 7.8Mit/s 0.0s
optimizer: 'optimizer=auto' found, ignoring 'lr0=0.01' and 'momentum=0.937' and determining best 'optimizer', 'lr0' and 'momentum' automatically...
optimizer: AdamW(lr=0.00125, momentum=0.9) with parameter groups 39 weight(decay=0.0), 40 weight(decay=0.0005), 40 bias(decay=0.0)
Image sizes 224 train, 224 val
Using 2 dataloader workers
Logging results to /content/drive/MyDrive/shrimp_disease_images/baseline_model_comparison/yolo_runs/yolo26n-cls
Starting training for 15 epochs...

      Epoch    GPU_mem       loss  Instances       Size
       1/15     0.391G      1.287          4        224: 100% ━━━━━━━━━━━━ 26/26 2.1s/it 55.4s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 3/3 19.2it/s 0.2s
                   all      0.581          1

      Epoch    GPU_mem       loss  Instances       Size
       2/15      0.49G     0.9894          4        224: 100% ━━━━━━━━━━━━ 26/26 1.6s/it 40.9s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 3/3 19.8it/s 0.2s
                   all      0.616          1

      Epoch    GPU_mem       loss  Instances       Size
       3/15      0.49G     0.9189          4        224: 100% ━━━━━━━━━━━━ 26/26 1.7s/it 43.0s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 3/3 25.2it/s 0.1s
                   all      0.413          1

      Epoch    GPU_mem       loss  Instances       Size
       4/15      0.49G     0.8408          4        224: 100% ━━━━━━━━━━━━ 26/26 1.6s/it 42.5s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 3/3 35.2it/s 0.1s
                   all      0.506          1

      Epoch    GPU_mem       loss  Instances       Size
       5/15      0.49G     0.8228          4        224: 100% ━━━━━━━━━━━━ 26/26 1.6s/it 42.3s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 3/3 43.9it/s 0.1s
                   all      0.657          1

      Epoch    GPU_mem       loss  Instances       Size
       6/15      0.49G      0.763          4        224: 100% ━━━━━━━━━━━━ 26/26 1.6s/it 40.3s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 3/3 17.3it/s 0.2s
                   all      0.721          1

      Epoch    GPU_mem       loss  Instances       Size
       7/15      0.49G     0.6721          4        224: 100% ━━━━━━━━━━━━ 26/26 1.6s/it 42.6s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 3/3 23.7it/s 0.1s
                   all      0.715          1

      Epoch    GPU_mem       loss  Instances       Size
       8/15      0.49G     0.6491          4        224: 100% ━━━━━━━━━━━━ 26/26 1.7s/it 43.6s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 3/3 20.1it/s 0.1s
                   all      0.715          1

      Epoch    GPU_mem       loss  Instances       Size
       9/15      0.49G     0.6237          4        224: 100% ━━━━━━━━━━━━ 26/26 1.6s/it 40.4s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 3/3 16.0it/s 0.2s
                   all      0.767          1

      Epoch    GPU_mem       loss  Instances       Size
      10/15      0.49G      0.536          4        224: 100% ━━━━━━━━━━━━ 26/26 1.6s/it 41.5s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 3/3 25.3it/s 0.1s
                   all      0.733          1

      Epoch    GPU_mem       loss  Instances       Size
      11/15      0.49G     0.5433          4        224: 100% ━━━━━━━━━━━━ 26/26 1.6s/it 42.2s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 3/3 22.1it/s 0.1s
                   all       0.75          1

      Epoch    GPU_mem       loss  Instances       Size
      12/15      0.49G     0.4827          4        224: 100% ━━━━━━━━━━━━ 26/26 1.6s/it 42.3s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 3/3 22.5it/s 0.1s
                   all      0.785          1

      Epoch    GPU_mem       loss  Instances       Size
      13/15      0.49G     0.4681          4        224: 100% ━━━━━━━━━━━━ 26/26 1.7s/it 43.2s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 3/3 19.3it/s 0.2s
                   all      0.767          1

      Epoch    GPU_mem       loss  Instances       Size
      14/15      0.49G     0.4474          4        224: 100% ━━━━━━━━━━━━ 26/26 1.6s/it 41.6s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 3/3 13.9it/s 0.2s
                   all      0.791          1

      Epoch    GPU_mem       loss  Instances       Size
      15/15      0.49G     0.3726          4        224: 100% ━━━━━━━━━━━━ 26/26 1.6s/it 41.0s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 3/3 31.1it/s 0.1s
                   all      0.785          1

15 epochs completed in 0.185 hours.
Optimizer stripped from /content/drive/MyDrive/shrimp_disease_images/baseline_model_comparison/yolo_runs/yolo26n-cls/weights/last.pt, 3.2MB
Optimizer stripped from /content/drive/MyDrive/shrimp_disease_images/baseline_model_comparison/yolo_runs/yolo26n-cls/weights/best.pt, 3.2MB

Validating /content/drive/MyDrive/shrimp_disease_images/baseline_model_comparison/yolo_runs/yolo26n-cls/weights/best.pt...
Ultralytics 8.4.51 🚀 Python-3.12.13 torch-2.10.0+cu128 CUDA:0 (Tesla T4, 14913MiB)
YOLO26n-cls summary (fused): 47 layers, 1,531,148 parameters, 0 gradients, 3.2 GFLOPs
train: /content/drive/MyDrive/shrimp_disease_images/baseline_model_comparison/yolo_dataset/train... found 804 images in 4 classes ✅
val: /content/drive/MyDrive/shrimp_disease_images/baseline_model_comparison/yolo_dataset/val... found 172 images in 4 classes ✅
test: /content/drive/MyDrive/shrimp_disease_images/baseline_model_comparison/yolo_dataset/test... found 173 images in 4 classes ✅
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 3/3 9.1it/s 0.3s
                   all      0.791          1
Speed: 0.3ms preprocess, 1.1ms inference, 0.0ms loss, 0.0ms postprocess per image
Results saved to /content/drive/MyDrive/shrimp_disease_images/baseline_model_comparison/yolo_runs/yolo26n-cls
Ultralytics 8.4.51 🚀 Python-3.12.13 torch-2.10.0+cu128 CPU (Intel Xeon CPU @ 2.00GHz)

PyTorch: starting from '/content/drive/MyDrive/shrimp_disease_images/baseline_model_comparison/yolo_runs/yolo26n-cls/weights/best.pt' with input shape (1, 3, 224, 224) BCHW and output shape(s) (1, 4) (3.0 MB)

ONNX: starting export with onnx 1.21.0 opset 20...
ONNX: slimming with onnxslim 0.1.93...
ONNX: export success ✅ 5.0s, saved as '/content/drive/MyDrive/shrimp_disease_images/baseline_model_comparison/yolo_runs/yolo26n-cls/weights/best.onnx' (5.9 MB)

TensorFlow SavedModel: starting export with tensorflow 2.20.0...
TensorFlow SavedModel: starting TFLite export with onnx2tf 1.28.8...
Saved artifact at '/content/drive/MyDrive/shrimp_disease_images/baseline_model_comparison/yolo_runs/yolo26n-cls/weights/best_saved_model'. The following endpoints are available:

* Endpoint 'serving_default'
  inputs_0 (POSITIONAL_ONLY): TensorSpec(shape=(1, 224, 224, 3), dtype=tf.float32, name='images')
Output Type:
  TensorSpec(shape=(1, 4), dtype=tf.float32, name=None)
Captures:
  133867685389776: TensorSpec(shape=(4, 2), dtype=tf.int32, name=None)
  133867685391120: TensorSpec(shape=(3, 3, 3, 16), dtype=tf.float32, name=None)
  133867685389008: TensorSpec(shape=(16,), dtype=tf.float32, name=None)
  133867685390736: TensorSpec(shape=(4, 2), dtype=tf.int32, name=None)
  133867685395152: TensorSpec(shape=(3, 3, 16, 32), dtype=tf.float32, name=None)
  133867685387856: TensorSpec(shape=(32,), dtype=tf.float32, name=None)
  133867685391312: TensorSpec(shape=(1, 1, 32, 32), dtype=tf.float32, name=None)
  133867685390544: TensorSpec(shape=(32,), dtype=tf.float32, name=None)
  133867685388432: TensorSpec(shape=(4,), dtype=tf.int64, name=None)
  133867685389392: TensorSpec(shape=(4,), dtype=tf.int64, name=None)
  133867685386704: TensorSpec(shape=(3, 3, 16, 8), dtype=tf.float32, name=None)
  133867685386320: TensorSpec(shape=(8,), dtype=tf.float32, name=None)
  133867685389584: TensorSpec(shape=(3, 3, 8, 16), dtype=tf.float32, name=None)
  133867685390160: TensorSpec(shape=(16,), dtype=tf.float32, name=None)
  133867685388240: TensorSpec(shape=(4,), dtype=tf.int64, name=None)
  133867685387472: TensorSpec(shape=(4,), dtype=tf.int64, name=None)
  133867685384592: TensorSpec(shape=(1, 1, 48, 64), dtype=tf.float32, name=None)
  133867685387280: TensorSpec(shape=(64,), dtype=tf.float32, name=None)
  133867685386512: TensorSpec(shape=(4, 2), dtype=tf.int32, name=None)
  133867685387088: TensorSpec(shape=(3, 3, 64, 64), dtype=tf.float32, name=None)
  133867685385744: TensorSpec(shape=(64,), dtype=tf.float32, name=None)
  133867685384976: TensorSpec(shape=(1, 1, 64, 64), dtype=tf.float32, name=None)
  133867685381136: TensorSpec(shape=(64,), dtype=tf.float32, name=None)
  133867685385552: TensorSpec(shape=(4,), dtype=tf.int64, name=None)
  133867685384016: TensorSpec(shape=(4,), dtype=tf.int64, name=None)
  133867685382288: TensorSpec(shape=(3, 3, 32, 16), dtype=tf.float32, name=None)
  133867685382864: TensorSpec(shape=(16,), dtype=tf.float32, name=None)
  133867685383632: TensorSpec(shape=(3, 3, 16, 32), dtype=tf.float32, name=None)
  133867685388048: TensorSpec(shape=(32,), dtype=tf.float32, name=None)
  133867685380752: TensorSpec(shape=(4,), dtype=tf.int64, name=None)
  133867685383248: TensorSpec(shape=(4,), dtype=tf.int64, name=None)
  133867685381712: TensorSpec(shape=(1, 1, 96, 128), dtype=tf.float32, name=None)
  133867685382096: TensorSpec(shape=(128,), dtype=tf.float32, name=None)
  133867685380368: TensorSpec(shape=(4, 2), dtype=tf.int32, name=None)
  133867685382480: TensorSpec(shape=(3, 3, 128, 128), dtype=tf.float32, name=None)
  133867685381520: TensorSpec(shape=(128,), dtype=tf.float32, name=None)
  133867685380944: TensorSpec(shape=(1, 1, 128, 128), dtype=tf.float32, name=None)
  133867685384400: TensorSpec(shape=(128,), dtype=tf.float32, name=None)
  133867685384784: TensorSpec(shape=(4,), dtype=tf.int64, name=None)
  133867685383824: TensorSpec(shape=(4,), dtype=tf.int64, name=None)
  133867685380560: TensorSpec(shape=(1, 1, 64, 32), dtype=tf.float32, name=None)
  133867685380176: TensorSpec(shape=(32,), dtype=tf.float32, name=None)
  133867685385168: TensorSpec(shape=(3, 3, 32, 32), dtype=tf.float32, name=None)
  133868178783312: TensorSpec(shape=(32,), dtype=tf.float32, name=None)
  133868178780816: TensorSpec(shape=(3, 3, 32, 32), dtype=tf.float32, name=None)
  133868178776976: TensorSpec(shape=(32,), dtype=tf.float32, name=None)
  133868178776016: TensorSpec(shape=(3, 3, 32, 32), dtype=tf.float32, name=None)
  133868178776784: TensorSpec(shape=(32,), dtype=tf.float32, name=None)
  133868178779280: TensorSpec(shape=(3, 3, 32, 32), dtype=tf.float32, name=None)
  133867685386128: TensorSpec(shape=(1, 1, 64, 32), dtype=tf.float32, name=None)
  133868178781776: TensorSpec(shape=(32,), dtype=tf.float32, name=None)
  133867685383056: TensorSpec(shape=(32,), dtype=tf.float32, name=None)
  133868178777168: TensorSpec(shape=(1, 1, 64, 64), dtype=tf.float32, name=None)
  133868178781584: TensorSpec(shape=(64,), dtype=tf.float32, name=None)
  133867685384208: TensorSpec(shape=(4,), dtype=tf.int64, name=None)
  133867685385360: TensorSpec(shape=(4,), dtype=tf.int64, name=None)
  133868178780624: TensorSpec(shape=(1, 1, 192, 128), dtype=tf.float32, name=None)
  133868178782736: TensorSpec(shape=(128,), dtype=tf.float32, name=None)
  133868178783888: TensorSpec(shape=(4, 2), dtype=tf.int32, name=None)
  133868178782928: TensorSpec(shape=(3, 3, 128, 256), dtype=tf.float32, name=None)
  133868178779088: TensorSpec(shape=(256,), dtype=tf.float32, name=None)
  133868178777936: TensorSpec(shape=(1, 1, 256, 256), dtype=tf.float32, name=None)
  133868178780240: TensorSpec(shape=(256,), dtype=tf.float32, name=None)
  133868178777744: TensorSpec(shape=(4,), dtype=tf.int64, name=None)
  133868178776400: TensorSpec(shape=(4,), dtype=tf.int64, name=None)
  133868178783120: TensorSpec(shape=(1, 1, 128, 64), dtype=tf.float32, name=None)
  133868178781968: TensorSpec(shape=(64,), dtype=tf.float32, name=None)
  133868178774096: TensorSpec(shape=(3, 3, 64, 64), dtype=tf.float32, name=None)
  133868178779664: TensorSpec(shape=(64,), dtype=tf.float32, name=None)
  133868178783504: TensorSpec(shape=(3, 3, 64, 64), dtype=tf.float32, name=None)
  133868178779472: TensorSpec(shape=(64,), dtype=tf.float32, name=None)
  133868178774288: TensorSpec(shape=(3, 3, 64, 64), dtype=tf.float32, name=None)
  133868178776592: TensorSpec(shape=(64,), dtype=tf.float32, name=None)
  133868178770640: TensorSpec(shape=(3, 3, 64, 64), dtype=tf.float32, name=None)
  133868178776208: TensorSpec(shape=(1, 1, 128, 64), dtype=tf.float32, name=None)
  133868178781200: TensorSpec(shape=(64,), dtype=tf.float32, name=None)
  133868178773904: TensorSpec(shape=(64,), dtype=tf.float32, name=None)
  133868178782544: TensorSpec(shape=(1, 1, 128, 128), dtype=tf.float32, name=None)
  133868178783696: TensorSpec(shape=(128,), dtype=tf.float32, name=None)
  133868178778704: TensorSpec(shape=(4,), dtype=tf.int64, name=None)
  133868178781392: TensorSpec(shape=(4,), dtype=tf.int64, name=None)
  133868178780432: TensorSpec(shape=(1, 1, 384, 256), dtype=tf.float32, name=None)
  133868178779856: TensorSpec(shape=(256,), dtype=tf.float32, name=None)
  133868178782160: TensorSpec(shape=(1, 1, 256, 256), dtype=tf.float32, name=None)
  133868178781008: TensorSpec(shape=(256,), dtype=tf.float32, name=None)
  133868178777552: TensorSpec(shape=(1, 1, 128, 256), dtype=tf.float32, name=None)
  133868178780048: TensorSpec(shape=(256,), dtype=tf.float32, name=None)
  133868178778128: TensorSpec(shape=(), dtype=tf.resource, name=None)
  133868326763792: TensorSpec(shape=(128,), dtype=tf.float32, name=None)
  133868326763984: TensorSpec(shape=(1, 1, 128, 128), dtype=tf.float32, name=None)
  133868178778896: TensorSpec(shape=(128,), dtype=tf.float32, name=None)
  133868178778320: TensorSpec(shape=(1, 1, 128, 256), dtype=tf.float32, name=None)
  133867725096144: TensorSpec(shape=(256,), dtype=tf.float32, name=None)
  133867725108816: TensorSpec(shape=(1, 1, 256, 128), dtype=tf.float32, name=None)
  133867725095568: TensorSpec(shape=(128,), dtype=tf.float32, name=None)
  133867725109200: TensorSpec(shape=(1, 1, 256, 256), dtype=tf.float32, name=None)
  133867725107280: TensorSpec(shape=(256,), dtype=tf.float32, name=None)
  133867725103824: TensorSpec(shape=(1, 1, 256, 1280), dtype=tf.float32, name=None)
  133867725100944: TensorSpec(shape=(1280,), dtype=tf.float32, name=None)
  133867725101520: TensorSpec(shape=(1280, 4), dtype=tf.float32, name=None)
  133867725103056: TensorSpec(shape=(), dtype=tf.float32, name=None)
  133867725098064: TensorSpec(shape=(4,), dtype=tf.float32, name=None)
TensorFlow SavedModel: export success ✅ 12.7s, saved as '/content/drive/MyDrive/shrimp_disease_images/baseline_model_comparison/yolo_runs/yolo26n-cls/weights/best_saved_model' (14.8 MB)

TensorFlow Lite: starting export with tensorflow 2.20.0...
TensorFlow Lite: export success ✅ 0.0s, saved as '/content/drive/MyDrive/shrimp_disease_images/baseline_model_comparison/yolo_runs/yolo26n-cls/weights/best_saved_model/best_float32.tflite' (5.9 MB)

Export complete (13.7s)
Results saved to /content/drive/MyDrive/shrimp_disease_images/baseline_model_comparison/yolo_runs/yolo26n-cls/weights/best_saved_model/best_float32.tflite

,Model,Parameters (M),Training Time (s),Val F1-Score,Test Accuracy,Test F1-Score,Inference Time (s),FPS,Latency (ms),Export Format,Export Path,Export Note
0,yolo26n-cls,1.53,680.4,0.7742,0.815,0.8073,17.93,9.7,103.62,tflite,/content/drive/MyDrive/shrimp_disease_images/b...,

================================================================================
Training YOLO baseline: yolo26m-cls
================================================================================
Downloading https://github.com/ultralytics/assets/releases/download/v8.4.0/yolo26m-cls.pt to 'yolo26m-cls.pt': 100% ━━━━━━━━━━━━ 22.4MB 38.7MB/s 0.6s
Ultralytics 8.4.51 🚀 Python-3.12.13 torch-2.10.0+cu128 CUDA:0 (Tesla T4, 14913MiB)
engine/trainer: agnostic_nms=False, amp=True, angle=1.0, augment=False, auto_augment=randaugment, batch=32, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, cls_pw=0.0, compile=False, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=/content/drive/MyDrive/shrimp_disease_images/baseline_model_comparison/yolo_dataset, degrees=0.0, deterministic=True, device=0, dfl=1.5, dnn=False, dropout=0.0, dynamic=False, embed=None, end2end=None, epochs=15, erasing=0.4, exist_ok=True, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=None, half=False, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=224, int8=False, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolo26m-cls.pt, momentum=0.937, mosaic=1.0, multi_scale=0.0, name=yolo26m-cls, nbs=64, nms=False, opset=None, optimize=False, optimizer=auto, overlap_mask=True, patience=3, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=/content/drive/MyDrive/shrimp_disease_images/baseline_model_comparison/yolo_runs, rect=False, resume=False, retina_masks=False, rle=1.0, save=True, save_conf=False, save_crop=False, save_dir=/content/drive/MyDrive/shrimp_disease_images/baseline_model_comparison/yolo_runs/yolo26m-cls, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=42, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=classify, time=None, tracker=botsort.yaml, translate=0.1, val=True, verbose=True, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0005, workers=8, workspace=None
train: /content/drive/MyDrive/shrimp_disease_images/baseline_model_comparison/yolo_dataset/train... found 804 images in 4 classes ✅
val: /content/drive/MyDrive/shrimp_disease_images/baseline_model_comparison/yolo_dataset/val... found 172 images in 4 classes ✅
test: /content/drive/MyDrive/shrimp_disease_images/baseline_model_comparison/yolo_dataset/test... found 173 images in 4 classes ✅
Overriding model.yaml nc=1000 with nc=4

                   from  n    params  module                                       arguments
  0                  -1  1      1856  ultralytics.nn.modules.conv.Conv             [3, 64, 3, 2]
  1                  -1  1     73984  ultralytics.nn.modules.conv.Conv             [64, 128, 3, 2]
  2                  -1  1    111872  ultralytics.nn.modules.block.C3k2            [128, 256, 1, True, 0.25]
  3                  -1  1    590336  ultralytics.nn.modules.conv.Conv             [256, 256, 3, 2]
  4                  -1  1    444928  ultralytics.nn.modules.block.C3k2            [256, 512, 1, True, 0.25]
  5                  -1  1   2360320  ultralytics.nn.modules.conv.Conv             [512, 512, 3, 2]
  6                  -1  1   1380352  ultralytics.nn.modules.block.C3k2            [512, 512, 1, True]
  7                  -1  1   2360320  ultralytics.nn.modules.conv.Conv             [512, 512, 3, 2]
  8                  -1  1   1380352  ultralytics.nn.modules.block.C3k2            [512, 512, 1, True]
  9                  -1  1    990976  ultralytics.nn.modules.block.C2PSA           [512, 512, 1]
 10                  -1  1    663044  ultralytics.nn.modules.head.Classify         [512, 4]
YOLO26m-cls summary: 106 layers, 10,358,340 parameters, 10,358,340 gradients, 39.6 GFLOPs
Transferred 294/296 items from pretrained weights
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: checks passed ✅
train: Fast image access ✅ (ping: 0.5±0.1 ms, read: 10.9±5.1 MB/s, size: 119.3 KB)
train: Scanning /content/drive/MyDrive/shrimp_disease_images/baseline_model_comparison/yolo_dataset/train... 804 images, 0 corrupt: 100% ━━━━━━━━━━━━ 804/804 306.6Mit/s 0.0s
val: Fast image access ✅ (ping: 0.8±0.2 ms, read: 13.2±4.0 MB/s, size: 119.2 KB)
val: Scanning /content/drive/MyDrive/shrimp_disease_images/baseline_model_comparison/yolo_dataset/val... 172 images, 0 corrupt: 100% ━━━━━━━━━━━━ 172/172 7.1Mit/s 0.0s
optimizer: 'optimizer=auto' found, ignoring 'lr0=0.01' and 'momentum=0.937' and determining best 'optimizer', 'lr0' and 'momentum' automatically...
optimizer: AdamW(lr=0.00125, momentum=0.9) with parameter groups 49 weight(decay=0.0), 50 weight(decay=0.0005), 50 bias(decay=0.0)
Image sizes 224 train, 224 val
Using 2 dataloader workers
Logging results to /content/drive/MyDrive/shrimp_disease_images/baseline_model_comparison/yolo_runs/yolo26m-cls
Starting training for 15 epochs...

      Epoch    GPU_mem       loss  Instances       Size
       1/15      1.43G      1.287          4        224: 100% ━━━━━━━━━━━━ 26/26 2.2s/it 58.2s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 3/3 12.6it/s 0.2s
                   all       0.64          1

      Epoch    GPU_mem       loss  Instances       Size
       2/15      1.78G     0.9337          4        224: 100% ━━━━━━━━━━━━ 26/26 1.6s/it 41.5s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 3/3 16.7it/s 0.2s
                   all       0.64          1

      Epoch    GPU_mem       loss  Instances       Size
       3/15      1.78G     0.8645          4        224: 100% ━━━━━━━━━━━━ 26/26 1.7s/it 45.0s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 3/3 16.6it/s 0.2s
                   all      0.535          1

      Epoch    GPU_mem       loss  Instances       Size
       4/15      1.78G     0.8287          4        224: 100% ━━━━━━━━━━━━ 26/26 1.6s/it 42.8s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 3/3 15.2it/s 0.2s
                   all      0.547          1
EarlyStopping: Training stopped early as no improvement observed in last 3 epochs. Best results observed at epoch 1, best model saved as best.pt.
To update EarlyStopping(patience=3) pass a new patience value, i.e. `patience=300` or use `patience=0` to disable EarlyStopping.

4 epochs completed in 0.056 hours.
Optimizer stripped from /content/drive/MyDrive/shrimp_disease_images/baseline_model_comparison/yolo_runs/yolo26m-cls/weights/last.pt, 20.9MB
Optimizer stripped from /content/drive/MyDrive/shrimp_disease_images/baseline_model_comparison/yolo_runs/yolo26m-cls/weights/best.pt, 20.9MB

Validating /content/drive/MyDrive/shrimp_disease_images/baseline_model_comparison/yolo_runs/yolo26m-cls/weights/best.pt...
Ultralytics 8.4.51 🚀 Python-3.12.13 torch-2.10.0+cu128 CUDA:0 (Tesla T4, 14913MiB)
YOLO26m-cls summary (fused): 57 layers, 10,346,756 parameters, 0 gradients, 39.3 GFLOPs
train: /content/drive/MyDrive/shrimp_disease_images/baseline_model_comparison/yolo_dataset/train... found 804 images in 4 classes ✅
val: /content/drive/MyDrive/shrimp_disease_images/baseline_model_comparison/yolo_dataset/val... found 172 images in 4 classes ✅
test: /content/drive/MyDrive/shrimp_disease_images/baseline_model_comparison/yolo_dataset/test... found 173 images in 4 classes ✅
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 3/3 10.6it/s 0.3s
                   all       0.64          1
Speed: 0.1ms preprocess, 1.2ms inference, 0.0ms loss, 0.0ms postprocess per image
Results saved to /content/drive/MyDrive/shrimp_disease_images/baseline_model_comparison/yolo_runs/yolo26m-cls
Ultralytics 8.4.51 🚀 Python-3.12.13 torch-2.10.0+cu128 CPU (Intel Xeon CPU @ 2.00GHz)

PyTorch: starting from '/content/drive/MyDrive/shrimp_disease_images/baseline_model_comparison/yolo_runs/yolo26m-cls/weights/best.pt' with input shape (1, 3, 224, 224) BCHW and output shape(s) (1, 4) (19.9 MB)

ONNX: starting export with onnx 1.21.0 opset 20...
ONNX: slimming with onnxslim 0.1.93...
ONNX: export success ✅ 1.7s, saved as '/content/drive/MyDrive/shrimp_disease_images/baseline_model_comparison/yolo_runs/yolo26m-cls/weights/best.onnx' (39.5 MB)

TensorFlow SavedModel: starting export with tensorflow 2.20.0...
TensorFlow SavedModel: starting TFLite export with onnx2tf 1.28.8...
Saved artifact at '/content/drive/MyDrive/shrimp_disease_images/baseline_model_comparison/yolo_runs/yolo26m-cls/weights/best_saved_model'. The following endpoints are available:

* Endpoint 'serving_default'
  inputs_0 (POSITIONAL_ONLY): TensorSpec(shape=(1, 224, 224, 3), dtype=tf.float32, name='images')
Output Type:
  TensorSpec(shape=(1, 4), dtype=tf.float32, name=None)
Captures:
  133867725097872: TensorSpec(shape=(4, 2), dtype=tf.int32, name=None)
  133867725106128: TensorSpec(shape=(3, 3, 3, 64), dtype=tf.float32, name=None)
  133867725108432: TensorSpec(shape=(64,), dtype=tf.float32, name=None)
  133867725110352: TensorSpec(shape=(4, 2), dtype=tf.int32, name=None)
  133867725105168: TensorSpec(shape=(3, 3, 64, 128), dtype=tf.float32, name=None)
  133867725108240: TensorSpec(shape=(128,), dtype=tf.float32, name=None)
  133867725107088: TensorSpec(shape=(1, 1, 128, 128), dtype=tf.float32, name=None)
  133867725105360: TensorSpec(shape=(128,), dtype=tf.float32, name=None)
  133867725109968: TensorSpec(shape=(4,), dtype=tf.int64, name=None)
  133867725105936: TensorSpec(shape=(4,), dtype=tf.int64, name=None)
  133867725102096: TensorSpec(shape=(1, 1, 64, 32), dtype=tf.float32, name=None)
  133867725100752: TensorSpec(shape=(32,), dtype=tf.float32, name=None)
  133867725101904: TensorSpec(shape=(3, 3, 32, 32), dtype=tf.float32, name=None)
  133867725102672: TensorSpec(shape=(32,), dtype=tf.float32, name=None)
  133867725104400: TensorSpec(shape=(3, 3, 32, 32), dtype=tf.float32, name=None)
  133867725103248: TensorSpec(shape=(32,), dtype=tf.float32, name=None)
  133867725107472: TensorSpec(shape=(3, 3, 32, 32), dtype=tf.float32, name=None)
  133867725099600: TensorSpec(shape=(32,), dtype=tf.float32, name=None)
  133867725101328: TensorSpec(shape=(3, 3, 32, 32), dtype=tf.float32, name=None)
  133867725102480: TensorSpec(shape=(1, 1, 64, 32), dtype=tf.float32, name=None)
  133867725101712: TensorSpec(shape=(32,), dtype=tf.float32, name=None)
  133867725106512: TensorSpec(shape=(32,), dtype=tf.float32, name=None)
  133867725100176: TensorSpec(shape=(1, 1, 64, 64), dtype=tf.float32, name=None)
  133867725099792: TensorSpec(shape=(64,), dtype=tf.float32, name=None)
  133867725109008: TensorSpec(shape=(4,), dtype=tf.int64, name=None)
  133867725107664: TensorSpec(shape=(4,), dtype=tf.int64, name=None)
  133867725101136: TensorSpec(shape=(1, 1, 192, 256), dtype=tf.float32, name=None)
  133867725096336: TensorSpec(shape=(256,), dtype=tf.float32, name=None)
  133867725103632: TensorSpec(shape=(4, 2), dtype=tf.int32, name=None)
  133867725100560: TensorSpec(shape=(3, 3, 256, 256), dtype=tf.float32, name=None)
  133867725100368: TensorSpec(shape=(256,), dtype=tf.float32, name=None)
  133867725099024: TensorSpec(shape=(1, 1, 256, 256), dtype=tf.float32, name=None)
  133867725104784: TensorSpec(shape=(256,), dtype=tf.float32, name=None)
  133867725104208: TensorSpec(shape=(4,), dtype=tf.int64, name=None)
  133867725096528: TensorSpec(shape=(4,), dtype=tf.int64, name=None)
  133867725098256: TensorSpec(shape=(1, 1, 128, 64), dtype=tf.float32, name=None)
  133867725110736: TensorSpec(shape=(64,), dtype=tf.float32, name=None)
  133867725095760: TensorSpec(shape=(3, 3, 64, 64), dtype=tf.float32, name=None)
  133867725098640: TensorSpec(shape=(64,), dtype=tf.float32, name=None)
  133867725095184: TensorSpec(shape=(3, 3, 64, 64), dtype=tf.float32, name=None)
  133867725097680: TensorSpec(shape=(64,), dtype=tf.float32, name=None)
  133867725110928: TensorSpec(shape=(3, 3, 64, 64), dtype=tf.float32, name=None)
  133867725098448: TensorSpec(shape=(64,), dtype=tf.float32, name=None)
  133867725099984: TensorSpec(shape=(3, 3, 64, 64), dtype=tf.float32, name=None)
  133867725104976: TensorSpec(shape=(1, 1, 128, 64), dtype=tf.float32, name=None)
  133867725095376: TensorSpec(shape=(64,), dtype=tf.float32, name=None)
  133867725099408: TensorSpec(shape=(64,), dtype=tf.float32, name=None)
  133867725103056: TensorSpec(shape=(1, 1, 128, 128), dtype=tf.float32, name=None)
  133867725095952: TensorSpec(shape=(128,), dtype=tf.float32, name=None)
  133867725104016: TensorSpec(shape=(4,), dtype=tf.int64, name=None)
  133867725094992: TensorSpec(shape=(4,), dtype=tf.int64, name=None)
  133867725101520: TensorSpec(shape=(1, 1, 384, 512), dtype=tf.float32, name=None)
  133867725100944: TensorSpec(shape=(512,), dtype=tf.float32, name=None)
  133867725103824: TensorSpec(shape=(4, 2), dtype=tf.int32, name=None)
  133867725109392: TensorSpec(shape=(3, 3, 512, 512), dtype=tf.float32, name=None)
  133867725098064: TensorSpec(shape=(512,), dtype=tf.float32, name=None)
  133867725109200: TensorSpec(shape=(1, 1, 512, 512), dtype=tf.float32, name=None)
  133867725095568: TensorSpec(shape=(512,), dtype=tf.float32, name=None)
  133867685391888: TensorSpec(shape=(4,), dtype=tf.int64, name=None)
  133867685393808: TensorSpec(shape=(4,), dtype=tf.int64, name=None)
  133867725096144: TensorSpec(shape=(1, 1, 256, 128), dtype=tf.float32, name=None)
  133867725107280: TensorSpec(shape=(128,), dtype=tf.float32, name=None)
  133867685395536: TensorSpec(shape=(3, 3, 128, 128), dtype=tf.float32, name=None)
  133867685395728: TensorSpec(shape=(128,), dtype=tf.float32, name=None)
  133867685394768: TensorSpec(shape=(3, 3, 128, 128), dtype=tf.float32, name=None)
  133867685392272: TensorSpec(shape=(128,), dtype=tf.float32, name=None)
  133867685393232: TensorSpec(shape=(3, 3, 128, 128), dtype=tf.float32, name=None)
  133867685394192: TensorSpec(shape=(128,), dtype=tf.float32, name=None)
  133867685393616: TensorSpec(shape=(3, 3, 128, 128), dtype=tf.float32, name=None)
  133867725108624: TensorSpec(shape=(1, 1, 256, 128), dtype=tf.float32, name=None)
  133867685394384: TensorSpec(shape=(128,), dtype=tf.float32, name=None)
  133867725108816: TensorSpec(shape=(128,), dtype=tf.float32, name=None)
  133867685387664: TensorSpec(shape=(1, 1, 256, 256), dtype=tf.float32, name=None)
  133867685396304: TensorSpec(shape=(256,), dtype=tf.float32, name=None)
  133867685395920: TensorSpec(shape=(4,), dtype=tf.int64, name=None)
  133867685395344: TensorSpec(shape=(4,), dtype=tf.int64, name=None)
  133867685386896: TensorSpec(shape=(1, 1, 768, 512), dtype=tf.float32, name=None)
  133867685394576: TensorSpec(shape=(512,), dtype=tf.float32, name=None)
  133867685388816: TensorSpec(shape=(4, 2), dtype=tf.int32, name=None)
  133867685388624: TensorSpec(shape=(3, 3, 512, 512), dtype=tf.float32, name=None)
  133867685389200: TensorSpec(shape=(512,), dtype=tf.float32, name=None)
  133867685381328: TensorSpec(shape=(1, 1, 512, 512), dtype=tf.float32, name=None)
  133867685381904: TensorSpec(shape=(512,), dtype=tf.float32, name=None)
  133867685384208: TensorSpec(shape=(4,), dtype=tf.int64, name=None)
  133867685385360: TensorSpec(shape=(4,), dtype=tf.int64, name=None)
  133867685381520: TensorSpec(shape=(1, 1, 256, 128), dtype=tf.float32, name=None)
  133867685382480: TensorSpec(shape=(128,), dtype=tf.float32, name=None)
  133867685384784: TensorSpec(shape=(3, 3, 128, 128), dtype=tf.float32, name=None)
  133867685380368: TensorSpec(shape=(128,), dtype=tf.float32, name=None)
  133867685382096: TensorSpec(shape=(3, 3, 128, 128), dtype=tf.float32, name=None)
  133867685381712: TensorSpec(shape=(128,), dtype=tf.float32, name=None)
  133867685384400: TensorSpec(shape=(3, 3, 128, 128), dtype=tf.float32, name=None)
  133867685380752: TensorSpec(shape=(128,), dtype=tf.float32, name=None)
  133867685380560: TensorSpec(shape=(3, 3, 128, 128), dtype=tf.float32, name=None)
  133867685383440: TensorSpec(shape=(1, 1, 256, 128), dtype=tf.float32, name=None)
  133867685388048: TensorSpec(shape=(128,), dtype=tf.float32, name=None)
  133867685382672: TensorSpec(shape=(128,), dtype=tf.float32, name=None)
  133867685382288: TensorSpec(shape=(1, 1, 256, 256), dtype=tf.float32, name=None)
  133867685383248: TensorSpec(shape=(256,), dtype=tf.float32, name=None)
  133867685383056: TensorSpec(shape=(4,), dtype=tf.int64, name=None)
  133867685386128: TensorSpec(shape=(4,), dtype=tf.int64, name=None)
  133867685384016: TensorSpec(shape=(1, 1, 768, 512), dtype=tf.float32, name=None)
  133867685385552: TensorSpec(shape=(512,), dtype=tf.float32, name=None)
  133867685383632: TensorSpec(shape=(1, 1, 512, 512), dtype=tf.float32, name=None)
  133867685381136: TensorSpec(shape=(512,), dtype=tf.float32, name=None)
  133867685385744: TensorSpec(shape=(1, 1, 256, 512), dtype=tf.float32, name=None)
  133867685382864: TensorSpec(shape=(512,), dtype=tf.float32, name=None)
  133867685384592: TensorSpec(shape=(), dtype=tf.resource, name=None)
  133867685386320: TensorSpec(shape=(256,), dtype=tf.float32, name=None)
  133867685386704: TensorSpec(shape=(1, 1, 256, 256), dtype=tf.float32, name=None)
  133867685390544: TensorSpec(shape=(256,), dtype=tf.float32, name=None)
  133867685389392: TensorSpec(shape=(1, 1, 256, 512), dtype=tf.float32, name=None)
  133867685391312: TensorSpec(shape=(512,), dtype=tf.float32, name=None)
  133867685384976: TensorSpec(shape=(1, 1, 512, 256), dtype=tf.float32, name=None)
  133867685387856: TensorSpec(shape=(256,), dtype=tf.float32, name=None)
  133867685388432: TensorSpec(shape=(1, 1, 512, 512), dtype=tf.float32, name=None)
  133867685387280: TensorSpec(shape=(512,), dtype=tf.float32, name=None)
  133867685387088: TensorSpec(shape=(1, 1, 512, 1280), dtype=tf.float32, name=None)
  133867685387472: TensorSpec(shape=(1280,), dtype=tf.float32, name=None)
  133867685390736: TensorSpec(shape=(1280, 4), dtype=tf.float32, name=None)
  133867685389008: TensorSpec(shape=(), dtype=tf.float32, name=None)
  133867685391120: TensorSpec(shape=(4,), dtype=tf.float32, name=None)
TensorFlow SavedModel: export success ✅ 14.1s, saved as '/content/drive/MyDrive/shrimp_disease_images/baseline_model_comparison/yolo_runs/yolo26m-cls/weights/best_saved_model' (98.9 MB)

TensorFlow Lite: starting export with tensorflow 2.20.0...
TensorFlow Lite: export success ✅ 0.0s, saved as '/content/drive/MyDrive/shrimp_disease_images/baseline_model_comparison/yolo_runs/yolo26m-cls/weights/best_saved_model/best_float32.tflite' (39.5 MB)

Export complete (14.4s)
Results saved to /content/drive/MyDrive/shrimp_disease_images/baseline_model_comparison/yolo_runs/yolo26m-cls/weights/best_saved_model/best_float32.tflite
Predict:         yolo predict task=classify model=/content/drive/MyDrive/shrimp_disease_images/baseline_model_comparison/yolo_runs/yolo26m-cls/weights/best_saved_model/best_float32.tflite imgsz=224
Validate:        yolo val task=classify model=/content/drive/MyDrive/shrimp_disease_images/baseline_model_comparison/yolo_runs/yolo26m-cls/weights/best_saved_model/best_float32.tflite imgsz=224 data=/content/drive/MyDrive/shrimp_disease_images/baseline_model_comparison/yolo_dataset
Visualize:       https://netron.app
Recorded result:

,Model,Parameters (M),Training Time (s),Val F1-Score,Test Accuracy,Test F1-Score,Inference Time (s),FPS,Latency (ms),Export Format,Export Path,Export Note
0,yolo26m-cls,10.35,218.8,0.6074,0.6185,0.5913,16.87,10.3,97.52,tflite,/content/drive/MyDrive/shrimp_disease_images/b...,

================================================================================
BASELINE PERFORMANCE SUMMARY: SHRIMP DISEASE CLASSIFICATION
================================================================================

,Model,Parameters (M),Training Time (s),Val F1-Score,Test Accuracy,Test F1-Score,Inference Time (s),FPS,Latency (ms),Export Format,Export Path,Export Note
0,yolo26n-cls,1.53,680.4,0.7742,0.8150,0.8073,17.93,9.7,103.62,tflite,/content/drive/MyDrive/shrimp_disease_images/b...,
1,efficientnet_b0,4.01,512.4,0.7782,0.7399,0.7232,8.05,21.5,46.51,onnx,/content/drive/MyDrive/shrimp_disease_images/b...,TFLite failed: ModuleNotFoundError: No module ...
2,yolo11n-cls,1.53,253.0,0.6360,0.6416,0.6226,17.79,9.7,102.84,tflite,/content/drive/MyDrive/shrimp_disease_images/b...,
3,yolo26m-cls,10.35,218.8,0.6074,0.6185,0.5913,16.87,10.3,97.52,tflite,/content/drive/MyDrive/shrimp_disease_images/b...,
4,yolo11m-cls,10.35,216.5,0.5309,0.6590,0.5600,16.08,10.8,92.94,tflite,/content/drive/MyDrive/shrimp_disease_images/b...,
5,mobilenet_v3_large,4.21,159.4,0.4293,0.4855,0.3906,6.14,28.2,35.51,onnx,/content/drive/MyDrive/shrimp_disease_images/b...,TFLite failed: ModuleNotFoundError: No module ...

Saved summary CSV: /content/drive/MyDrive/shrimp_disease_images/baseline_model_comparison/reports/baseline_model_comparison_summary.csv
Saved summary JSON: /content/drive/MyDrive/shrimp_disease_images/baseline_model_comparison/reports/baseline_model_comparison_summary.json

## Notes on interpreting this table

- `Val F1-Score` and `Test F1-Score` are **macro F1**, not micro F1. Macro F1 is more appropriate here because the shrimp disease classes are imbalanced and each class should contribute equally.
- `Training Time (s)` includes only the model's training phase. Export time is not included.
- `Inference Time (s)`, `FPS`, and `Latency (ms)` are measured over the shared test split after a short warm-up.
- `Export Format` reports `tflite` when LiteRT/TFLite export succeeds and `onnx` when the notebook falls back to ONNX. Check `Export Note` for conversion failures.
- The split is stratified and image-level. If specimen identifiers become available, rerun with a grouped split to better control leakage between photos of the same shrimp.